services:
  firefox:
    container_name: firefox
    environment:
    - PUID=1000
    - PGID=1000
    - TZ=Etc/UTC
    - CUSTOM_USER=user
    - PASSWORD=papayacherry2419
    image: lscr.io/linuxserver/firefox:latest
    ports:
    - 3000:3000
    - 3001:3001
    restart: unless-stopped
    security_opt:
    - seccomp:unconfined
    shm_size: 1gb
    volumes:
    - /Users/bansheetechnologiess.l./HomeDock/AppData/firefox:/config
version: '2.1'
