---
services:
  apprise-api:
    image: lscr.io/linuxserver/apprise-api:latest
    container_name: apprise-api
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/apprise-api:/config
    ports:
      - 8000:8000
    restart: unless-stopped
