---
version: "2.1"
services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest
    container_name: audacity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/audacity:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
