---
services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest
    container_name: audacity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE=Audacity
    volumes:
      - [[INSTALL_PATH]]/audacity:/config
    ports:
      - 3000:3000
    restart: unless-stopped
