---
version: "2.1"
services:
  boinc:
    image: lscr.io/linuxserver/boinc:latest
    container_name: boinc
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE=Boinc
    volumes:
      - [[INSTALL_PATH]]/boinc:/config
    ports:
      - 8080:8080
    restart: unless-stopped
