---
version: "2.1"
services:
  booksonic-air:
    image: lscr.io/linuxserver/booksonic-air:latest
    container_name: booksonic-air
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CONTEXT_PATH=url-base #optional
    volumes:
      - [[INSTALL_PATH]]/booksonic-air:/config
      - [[APP_MOUNT_POINT]]/booksonic-air/audiobooks:/audiobooks
      - [[APP_MOUNT_POINT]]/booksonic-air/podcasts:/podcasts
      - [[APP_MOUNT_POINT]]/booksonic-air/othermedia:/othermedia
    ports:
      - 4040:4040
    restart: unless-stopped
