---
version: "2.1"
services:
  chromium:
    image: lscr.io/linuxserver/chromium:latest
    container_name: chromium
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - CHROME_CLI=https://www.homedock.cloud/
    volumes:
      - [[INSTALL_PATH]]/chromium:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
