---
version: '3.3'
services:
  crafty:
    image: binhex/arch-crafty:latest
    container_name: crafty
    ports:
      - '8000:8000'
      - '25565-25575:25565-25575'
    volumes:
      - [[INSTALL_PATH]]/crafty:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - JAVA_VERSION=latest
      - UMASK=000
      - PUID=0
      - PGID=0
    restart: unless-stopped
