---
services:
  cura:
    image: lscr.io/linuxserver/cura:latest
    container_name: cura
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE=Cura
    volumes:
      - [[INSTALL_PATH]]/cura:/config
    ports:
      - 6466:3000
    restart: unless-stopped
