---
services:
  darktable:
    image: lscr.io/linuxserver/darktable:latest
    container_name: darktable
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE=Darktable
    volumes:
      - [[INSTALL_PATH]]/darktable:/config
    ports:
      - 7200:3000
    restart: unless-stopped
