---
version: "2.1"
services:
  davos:
    image: lscr.io/linuxserver/davos:latest
    container_name: davos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/davos:/config
      - [[APP_MOUNT_POINT]]/davos/downloads:/download
    ports:
      - 9090:8080
    restart: unless-stopped
