---
version: "2.1"
services:
  embystat:
    image: lscr.io/linuxserver/embystat:latest
    container_name: embystat
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/embystat:/config
    ports:
      - 6555:6555
    restart: unless-stopped
