---
version: "3.3"
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 8765:80
    volumes:
      - [[INSTALL_PATH]]/filebrowser:/config
      - [[APP_MOUNT_POINT]]/filebrowser:/srv
    environment:
      - TZ=UTC
