---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - FIREFOX_CLI=https://www.homedock.cloud/
    volumes:
      - [[INSTALL_PATH]]/firefox:/config
    ports:
      - 3000:3000
    shm_size: "1gb"
    restart: unless-stopped
