---
services:
  gitqlient:
    image: lscr.io/linuxserver/gitqlient:latest
    container_name: gitqlient
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
    volumes:
      - [[INSTALL_PATH]]/gitqlient:/config
    ports:
      - 3000:3000
      - 3001:3001
    restart: unless-stopped
