---
version: "2.1"
services:
  hedgedoc:
    image: lscr.io/linuxserver/hedgedoc:latest
    container_name: hedgedoc
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - "DB_HOST=[[LOCAL_IP]]
      - DB_PORT=3306
      - DB_USER=hedgedoc
      - "DB_PASS=[[HD_SYSTEM_PASSWORD]]"
      - DB_NAME=hedgedoc
      - CMD_DOMAIN=localhost
      - CMD_URL_ADDPORT=false #optional
      - CMD_PROTOCOL_USESSL=false #optional
      - CMD_PORT=3000 #optional
      - CMD_ALLOW_ORIGIN=['localhost'] #optional
    volumes:
      - [[INSTALL_PATH]]/hedgedoc:/config
    ports:
      - 3000:3000
    restart: unless-stopped
