---
services:
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - [[INSTALL_PATH]]/jackett:/config
      - [[APP_MOUNT_POINT]]/jackett/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
