---
version: "2.1"
services:
  mediaelch:
    image: lscr.io/linuxserver/mediaelch:latest
    container_name: mediaelch
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
    volumes:
      - [[INSTALL_PATH]]/mediaelch:/config
    ports:
      - 4848:3000
      - 4849:3001
    restart: unless-stopped
