---
version: "2.1"
services:
  mstream:
    image: lscr.io/linuxserver/mstream:latest
    container_name: mstream
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/mstream:/config
      - [[APP_MOUNT_POINT]]/mstream/music:/music
    ports:
      - 3000:3000
    restart: unless-stopped
