---
version: "2.1"
services:
  mysql-workbench:
    image: lscr.io/linuxserver/mysql-workbench:latest
    container_name: mysql-workbench
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
    volumes:
      - [[INSTALL_PATH]]/mysql-workbench:/config
    ports:
      - 3000:3000
      - 3001:3001
    cap_add:
      - IPC_LOCK
    restart: unless-stopped
