---
services:
  obsidian:
    image: lscr.io/linuxserver/obsidian:latest
    container_name: obsidian
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
    volumes:
      - [[INSTALL_PATH]]/obsidian:/config
    ports:
      - 41121:3000
      - 41122:3001
    shm_size: "1gb"
    restart: unless-stopped
