---
version: '3.3'
services:
  phantom:
    image: binhex/arch-phantom:latest
    container_name: phantom
    ports:
      - '19132:19132'
      - '19133:19133'
    volumes:
      - [[INSTALL_PATH]]/phantom:/config
      - /etc/localtime:/etc/localtime:ro
    environment:
      - REMOTE_MINECRAFT_IP=1.2.3.4
      - REMOTE_MINECRAFT_PORT=19132
      - CLEANUP_TIMEOUT=60
      - UMASK=000
      - PUID=0
      - PGID=0
