---
services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "35768:80/tcp"
    environment:
      TZ: 'America/Chicago'
      WEBPASSWORD: [[HD_PASSWORD]]
    volumes:
      - '[[INSTALL_PATH]]/pihole:/etc/pihole'
      - '[[INSTALL_PATH]]/pihole/dnsmasq:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: unless-stopped
