---
version: "2.1"
services:
  pwndrop:
    image: lscr.io/linuxserver/pwndrop:latest
    container_name: pwndrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SECRET_PATH=/pwndrop #optional
    volumes:
      - [[INSTALL_PATH]]/pwndrop:/config
    ports:
      - 8080:8080
    restart: unless-stopped
