---
version: "2.1"
services:
  quassel-core:
    image: lscr.io/linuxserver/quassel-core:latest
    container_name: quassel-core
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RUN_OPTS=--config-from-environment #optional
    volumes:
      - [[INSTALL_PATH]]/quassel-core:/config
    ports:
      - 4242:4242
      - 113:10113 #optional
    restart: unless-stopped
