---
version: '3.7'
services:
  rotki:
    container_name: rotki
    image: rotki/rotki:latest
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    stop_grace_period: 1m
    init: true
    ports:
      - 8235:80
    volumes:
      - [[INSTALL_PATH]]/rotki/data:/data
      - [[INSTALL_PATH]]/rotki/logs:/logs
    environment:
      - ROTKI_ACCEPT_DOCKER_RISK=1
