---
version: "2.1"
services:
  sickchill:
    image: lscr.io/linuxserver/sickchill:latest
    container_name: sickchill
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/sickchill:/config
      - [[APP_MOUNT_POINT]]/sickchill/downloads:/downloads
      - [[APP_MOUNT_POINT]]/sickchill/tv:/tv
    ports:
      - 8081:8081
    restart: unless-stopped
