---
version: '3.3'
services:
  wg-easy:
    container_name: wg-easy
    environment:
      - PORT=51821
      - HOST=0.0.0.0
      - INSECURE=true
      - SERVERURL=auto
    image: ghcr.io/wg-easy/wg-easy:15
    volumes:
    - [[INSTALL_PATH]]/wg-easy:/etc/wireguard
    - /lib/modules:/lib/modules:ro
    ports:
    - "51821:51821/tcp"
    - "51820:51820/udp"
    restart: unless-stopped
    cap_add:
    - NET_ADMIN
    - SYS_MODULE
    sysctls:
    - net.ipv4.ip_forward=1
    - net.ipv4.conf.all.src_valid_mark=1
    - net.ipv6.conf.all.disable_ipv6=0
    - net.ipv6.conf.all.forwarding=1
    - net.ipv6.conf.default.forwarding=1
