---
services:
  homedock:
    image: bansheetech/homedock-os:latest
    container_name: homedock-os
    restart: unless-stopped
    ports:
      - "13370:80"
      # - "13371:443" # Enable for Let's Encrypt SSL
    volumes:
      - ./homedock-data/DATA:/DATA
      - ./homedock-data/config:/homedock/config
      - ./homedock-data/compose:/homedock/compose-link
      - ./homedock-data/packages:/homedock/_user_packages
      - ./homedock-data/dropzone:/homedock/dropzone
      - ./homedock-data/logs:/homedock/logs
      - /var/run/docker.sock:/var/run/docker.sock
    extra_hosts:
      - "host.docker.internal:host-gateway"
    labels:
      - "HDDockerInDocker=true"
    environment:
      - TZ=Europe/Madrid
      - PYTHONUNBUFFERED=1
