version: '3.8'

services:
  tailscale:
    image: tailscale/tailscale
    container_name: tailscale
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - NET_RAW
    volumes:
      - /var/lib:/var/lib
      - /dev/net/tun:/dev/net/tun
    environment:
      - TS_AUTHKEY=tskey-auth-ab1CDE2CNTRL-0123456789abcdef
    restart: unless-stopped
    command: >
      sh -c "
      tailscaled & sleep 3 && tailscale up --authkey=tskey-auth-ab1CDE2CNTRL-0123456789abcdef
      "