// homedock-ui/vue3/static/js/__Data__/WhatsNewData.ts
// Copyright © 2023-2026 Banshee, All Rights Reserved
// See LICENSE.md or https://polyformproject.org/licenses/strict/1.0.0/
// https://www.banshee.pro

export type LocalizedText = { en: string } & Partial<Record<string, string>>;

export interface WhatsNewTag {
  key?: string;
  label?: string;
  text?: LocalizedText;
  accent?: boolean;
}

export interface WhatsNewEntry {
  icon: string;
  title: LocalizedText;
  body: LocalizedText;
  tag?: WhatsNewTag;
  image?: string;
  docsUrl?: string;
}

export interface WhatsNewSceneTile {
  icon: string;
  color: string;
}

export interface WhatsNewRelease {
  id: string;
  version: string;
  scene?: WhatsNewSceneTile[];
  title: LocalizedText;
  subtitle: LocalizedText;
  changelogUrl: string;
  entries: WhatsNewEntry[];
}

export function localized(text: LocalizedText, locale: string): string {
  return text[locale] || text.en;
}

const release26: WhatsNewRelease = {
  id: "container-terminal",
  version: "2.6",
  scene: [
    { icon: "terminal", color: "#6366f1" },
    { icon: "store", color: "#0ea5e9" },
    { icon: "office", color: "#16a34a" },
    { icon: "games", color: "#ec4899" },
  ],
  title: {
    en: "Terminal, Control Hub, a new App Store and our first games",
    es: "Terminal, Control Hub, una App Store nueva y nuestros primeros juegos",
    de: "Terminal, Control Hub, ein neuer App Store und unsere ersten Spiele",
    fr: "Terminal, Control Hub, un nouvel App Store et nos premiers jeux",
    it: "Terminale, Control Hub, un nuovo App Store e i nostri primi giochi",
    pt: "Terminal, Control Hub, uma App Store nova e os nossos primeiros jogos",
    ru: "Терминал, Control Hub, новый App Store и наши первые игры",
    uk: "Термінал, Control Hub, новий App Store і наші перші ігри",
    ja: "ターミナル、Control Hub、新しい App Store、そして初めてのゲーム",
    ko: "터미널, Control Hub, 새 App Store, 그리고 첫 게임",
    zh: "终端、Control Hub、全新的 App Store，以及我们的第一批游戏",
  },
  subtitle: {
    en: "Every app gets a shell, the App Store grows past 800 apps, and every document gets an editor.",
    es: "Cada app tiene su terminal, la App Store supera las 800 apps y cada documento tiene su editor.",
    de: "Jede App bekommt eine Shell, der App Store wächst auf über 800 Apps, und jedes Dokument bekommt einen Editor.",
    fr: "Chaque app a son terminal, l'App Store dépasse les 800 apps, et chaque document a son éditeur.",
    it: "Ogni app ha il suo terminale, l'App Store supera le 800 app e ogni documento ha il suo editor.",
    pt: "Cada app ganha um terminal, a App Store passa das 800 apps e cada documento ganha um editor.",
    ru: "У каждого приложения теперь есть терминал, в App Store больше 800 приложений, а у каждого документа есть редактор.",
    uk: "Кожен застосунок отримує термінал, в App Store понад 800 застосунків, а кожен документ отримує редактор.",
    ja: "すべてのアプリにシェルを、App Store には 800 以上のアプリを、すべての文書にエディターを。",
    ko: "모든 앱에 셸이, App Store에는 800개가 넘는 앱이, 모든 문서에 편집기가 생겼습니다.",
    zh: "每个应用都有了终端，App Store 超过 800 款应用，每份文档都有了编辑器。",
  },
  changelogUrl: "https://github.com/BansheeTech/HomeDockOS/blob/main/CHANGELOG.md",
  entries: [
    {
      icon: "terminal",
      tag: {
        accent: true,
        text: {
          en: "Container Terminal",
          es: "Terminal de contenedor",
          de: "Container-Terminal",
          fr: "Terminal de conteneur",
          it: "Terminale del container",
          pt: "Terminal de contêiner",
          ru: "Терминал контейнера",
          uk: "Термінал контейнера",
          ja: "コンテナターミナル",
          ko: "컨테이너 터미널",
          zh: "容器终端",
        },
      },
      image: "container-terminal.webp",
      title: {
        en: "Every app now has a terminal",
        es: "Cada app tiene ahora su terminal",
        de: "Jede App hat jetzt ein Terminal",
        fr: "Chaque app a désormais son terminal",
        it: "Ogni app ora ha un terminale",
        pt: "Cada app agora tem um terminal",
        ru: "У каждого приложения теперь есть терминал",
        uk: "Кожен застосунок тепер має термінал",
        ja: "すべてのアプリにターミナル",
        ko: "이제 모든 앱에 터미널이 있습니다",
        zh: "每个应用现在都有终端",
      },
      body: {
        en: "Right-click any app, dependencies included, and you get a real shell inside its container. It picks bash, ash or sh for you, and hangs up the moment you close the window.",
        es: "Haz clic derecho en cualquier app, dependencias incluidas, y tienes una shell de verdad dentro de su contenedor. Elige bash, ash o sh por ti y cuelga en cuanto cierras la ventana.",
        de: "Klicke mit rechts auf eine App, Abhängigkeiten inklusive, und du bekommst eine echte Shell in ihrem Container. Sie wählt bash, ash oder sh für dich und legt auf, sobald du das Fenster schließt.",
        fr: "Faites un clic droit sur n'importe quelle app, dépendances comprises, et vous obtenez un vrai shell dans son conteneur. Il choisit bash, ash ou sh pour vous et raccroche dès que vous fermez la fenêtre.",
        it: "Fai clic destro su qualsiasi app, dipendenze comprese, e ottieni una vera shell dentro il suo container. Sceglie bash, ash o sh per te e riattacca appena chiudi la finestra.",
        pt: "Clique com o botão direito em qualquer app, dependências incluídas, e você tem um shell de verdade dentro do contêiner. Ele escolhe bash, ash ou sh por você e desliga assim que você fecha a janela.",
        ru: "Щёлкните правой кнопкой по любому приложению, включая зависимости, и получите настоящую оболочку внутри его контейнера. Она сама выберет bash, ash или sh и завершится, как только вы закроете окно.",
        uk: "Клацніть правою кнопкою будь-який застосунок, залежності теж, і отримайте справжню оболонку всередині його контейнера. Вона сама обере bash, ash чи sh і завершиться, щойно ви закриєте вікно.",
        ja: "依存関係も含め、どのアプリでも右クリックすればコンテナ内の本物のシェルが開きます。bash、ash、sh を自動で選び、ウィンドウを閉じた瞬間にセッションを終了します。",
        ko: "의존성까지 포함해 어떤 앱이든 마우스 오른쪽 버튼을 누르면 컨테이너 안의 진짜 셸이 열립니다. bash, ash, sh 중 알맞은 것을 고르고, 창을 닫는 순간 세션을 끝냅니다.",
        zh: "右键点击任意应用（包括依赖），就能在它的容器里打开一个真正的 shell。它会替你选好 bash、ash 或 sh，关闭窗口的那一刻就会断开。",
      },
    },
    {
      icon: "opensource",
      tag: {
        accent: true,
        text: {
          en: "Built in the open, true this time",
          es: "Hecho en abierto, esta vez de verdad",
          de: "Offen entwickelt, diesmal wirklich",
          fr: "Développé au grand jour, pour de vrai cette fois",
          it: "Sviluppato alla luce del sole, stavolta davvero",
          pt: "Feito às claras, desta vez de verdade",
          ru: "Открытая разработка, на этот раз по-настоящему",
          uk: "Відкрита розробка, цього разу по-справжньому",
          ja: "オープンに開発、今度こそ本当に",
          ko: "공개적으로 개발, 이번엔 진짜로",
          zh: "公开开发，这次是真的",
        },
      },
      image: "prism-wm.webp",
      docsUrl: "https://github.com/BansheeTech/prism-wm",
      title: {
        en: "Prism Window Manager is open source",
        es: "Prism Window Manager ya es open source",
        de: "Prism Window Manager ist jetzt Open Source",
        fr: "Prism Window Manager est désormais open source",
        it: "Prism Window Manager ora è open source",
        pt: "O Prism Window Manager agora é open source",
        ru: "Prism Window Manager теперь с открытым исходным кодом",
        uk: "Prism Window Manager тепер із відкритим кодом",
        ja: "Prism Window Manager がオープンソースに",
        ko: "Prism Window Manager가 오픈 소스가 되었습니다",
        zh: "Prism Window Manager 现已开源",
      },
      body: {
        en: "The window manager behind every HomeDock OS window is now yours too. @prism-wm is on GitHub and npm under AGPL-3.0, with a framework-agnostic core and adapters for Vue 3, React and Svelte.",
        es: "El gestor de ventanas que mueve cada ventana de HomeDock OS ahora también es tuyo. @prism-wm está en GitHub y npm bajo licencia AGPL-3.0, con un núcleo independiente del framework y adaptadores para Vue 3, React y Svelte.",
        de: "Der Fenstermanager hinter jedem HomeDock-OS-Fenster gehört jetzt auch dir. @prism-wm ist auf GitHub und npm unter AGPL-3.0 verfügbar, mit einem frameworkunabhängigen Kern und Adaptern für Vue 3, React und Svelte.",
        fr: "Le gestionnaire de fenêtres derrière chaque fenêtre de HomeDock OS est désormais aussi le vôtre. @prism-wm est sur GitHub et npm sous licence AGPL-3.0, avec un cœur indépendant du framework et des adaptateurs pour Vue 3, React et Svelte.",
        it: "Il window manager dietro ogni finestra di HomeDock OS ora è anche tuo. @prism-wm è su GitHub e npm con licenza AGPL-3.0, con un core indipendente dal framework e adattatori per Vue 3, React e Svelte.",
        pt: "O gerenciador de janelas por trás de cada janela do HomeDock OS agora também é seu. O @prism-wm está no GitHub e no npm sob a licença AGPL-3.0, com um núcleo independente de framework e adaptadores para Vue 3, React e Svelte.",
        ru: "Оконный менеджер, который стоит за каждым окном HomeDock OS, теперь доступен и вам. @prism-wm опубликован на GitHub и npm под лицензией AGPL-3.0: ядро, не зависящее от фреймворка, и адаптеры для Vue 3, React и Svelte.",
        uk: "Віконний менеджер, що стоїть за кожним вікном HomeDock OS, тепер доступний і вам. @prism-wm опубліковано на GitHub і npm за ліцензією AGPL-3.0: ядро, незалежне від фреймворку, та адаптери для Vue 3, React і Svelte.",
        ja: "HomeDock OS のすべてのウィンドウを動かすウィンドウマネージャーが、あなたのものにもなりました。@prism-wm は AGPL-3.0 で GitHub と npm に公開され、フレームワークに依存しないコアと Vue 3、React、Svelte 用のアダプターを備えています。",
        ko: "HomeDock OS의 모든 창을 움직이는 윈도우 매니저를 이제 여러분도 쓸 수 있습니다. @prism-wm은 AGPL-3.0 라이선스로 GitHub와 npm에 공개되었으며, 프레임워크에 독립적인 코어와 Vue 3, React, Svelte용 어댑터를 제공합니다.",
        zh: "驱动 HomeDock OS 每一个窗口的窗口管理器，现在也属于你了。@prism-wm 已以 AGPL-3.0 许可证发布在 GitHub 和 npm 上，拥有与框架无关的核心，以及适用于 Vue 3、React 和 Svelte 的适配器。",
      },
    },
    {
      icon: "controlhub",
      tag: { key: "Control Hub", accent: true },
      image: "control-hub.webp",
      title: {
        en: "The Control Hub grew up into a Task Manager",
        es: "El Control Hub se ha hecho mayor: ahora es un Administrador de tareas",
        de: "Der Control Hub ist zum Task-Manager herangewachsen",
        fr: "Le Control Hub est devenu un vrai gestionnaire des tâches",
        it: "Il Control Hub è cresciuto ed è diventato un Task Manager",
        pt: "O Control Hub cresceu e virou um Gerenciador de Tarefas",
        ru: "Control Hub вырос в полноценный диспетчер задач",
        uk: "Control Hub виріс у повноцінний диспетчер завдань",
        ja: "Control Hub がタスクマネージャーに成長しました",
        ko: "Control Hub가 작업 관리자로 성장했습니다",
        zh: "Control Hub 长成了一个任务管理器",
      },
      body: {
        en: "Performance, Processes, App history, Dependencies and Details, with live graphs for CPU, memory, disk, network and temperature, and memory shown in real megabytes.",
        es: "Rendimiento, Procesos, Historial de apps, Dependencias y Detalles, con gráficas en vivo de CPU, memoria, disco, red y temperatura, y la memoria en megabytes de verdad.",
        de: "Leistung, Prozesse, App-Verlauf, Abhängigkeiten und Details, mit Live-Grafiken für CPU, Arbeitsspeicher, Datenträger, Netzwerk und Temperatur und Speicher in echten Megabyte.",
        fr: "Performances, Processus, Historique des apps, Dépendances et Détails, avec des graphiques en direct pour le processeur, la mémoire, le disque, le réseau et la température, et la mémoire en vrais mégaoctets.",
        it: "Prestazioni, Processi, Cronologia app, Dipendenze e Dettagli, con grafici dal vivo di CPU, memoria, disco, rete e temperatura, e la memoria in megabyte veri.",
        pt: "Desempenho, Processos, Histórico de apps, Dependências e Detalhes, com gráficos ao vivo de CPU, memória, disco, rede e temperatura, e a memória em megabytes de verdade.",
        ru: "Производительность, Процессы, Журнал приложений, Зависимости и Подробности: живые графики процессора, памяти, диска, сети и температуры, а память в настоящих мегабайтах.",
        uk: "Продуктивність, Процеси, Журнал застосунків, Залежності й Подробиці: живі графіки процесора, пам'яті, диска, мережі та температури, а пам'ять у справжніх мегабайтах.",
        ja: "パフォーマンス、プロセス、アプリの履歴、依存関係、詳細の 5 つのタブ。CPU、メモリ、ディスク、ネットワーク、温度をライブグラフで表示し、メモリは実際のメガバイトで表示します。",
        ko: "성능, 프로세스, 앱 기록, 의존성, 세부 정보 탭과 함께 CPU, 메모리, 디스크, 네트워크, 온도를 실시간 그래프로 보여 주고, 메모리는 실제 메가바이트로 표시합니다.",
        zh: "性能、进程、应用历史记录、依赖和详细信息五个标签页，CPU、内存、磁盘、网络和温度都有实时图表，内存以真实的 MB 显示。",
      },
    },
    {
      icon: "store",
      tag: { key: "App Store", accent: true },
      image: "app-store.webp",
      title: {
        en: "The App Store, rebuilt",
        es: "La App Store, rehecha",
        de: "Der App Store, neu gebaut",
        fr: "L'App Store, entièrement refait",
        it: "L'App Store, rifatto da capo",
        pt: "A App Store, refeita do zero",
        ru: "App Store, построенный заново",
        uk: "App Store, збудований наново",
        ja: "作り直した App Store",
        ko: "새로 만든 App Store",
        zh: "重做的 App Store",
      },
      body: {
        en: "A sidebar with Discover, categories and your Library, search that filters as you type, the download size of every app before you install it, and a warning when an app wasn't made for your server's processor.",
        es: "Una barra lateral con Descubrir, las categorías y tu Biblioteca, una búsqueda que filtra mientras escribes, el tamaño de descarga de cada app antes de instalarla y un aviso cuando una app no está hecha para el procesador de tu servidor.",
        de: "Eine Seitenleiste mit Entdecken, den Kategorien und deiner Bibliothek, eine Suche, die beim Tippen filtert, die Downloadgröße jeder App vor der Installation und eine Warnung, wenn eine App nicht für den Prozessor deines Servers gemacht ist.",
        fr: "Une barre latérale avec Découvrir, les catégories et votre Bibliothèque, une recherche qui filtre pendant la saisie, la taille de téléchargement de chaque app avant de l'installer, et un avertissement quand une app n'est pas faite pour le processeur de votre serveur.",
        it: "Una barra laterale con Scopri, le categorie e la tua Libreria, una ricerca che filtra mentre scrivi, la dimensione del download di ogni app prima di installarla e un avviso quando un'app non è fatta per il processore del tuo server.",
        pt: "Uma barra lateral com Descobrir, as categorias e a sua Biblioteca, uma busca que filtra enquanto você digita, o tamanho do download de cada app antes de instalar e um aviso quando um app não foi feito para o processador do seu servidor.",
        ru: "Боковая панель с «Обзором», категориями и вашей «Библиотекой», поиск, который фильтрует прямо при вводе, размер загрузки каждого приложения до установки и предупреждение, если приложение не рассчитано на процессор вашего сервера.",
        uk: "Бічна панель з «Оглядом», категоріями та вашою «Бібліотекою», пошук, що фільтрує просто під час введення, розмір завантаження кожного застосунку до встановлення і попередження, якщо застосунок не розрахований на процесор вашого сервера.",
        ja: "「見つける」、カテゴリ、ライブラリを並べたサイドバー、入力と同時に絞り込む検索、インストール前にわかる各アプリのダウンロードサイズ、そしてサーバーのプロセッサー向けに作られていないアプリへの警告。",
        ko: "둘러보기, 카테고리, 보관함을 담은 사이드바, 입력하는 대로 걸러 주는 검색, 설치 전에 보이는 앱별 다운로드 크기, 그리고 서버 프로세서에 맞지 않는 앱에 대한 경고.",
        zh: "侧边栏里有发现、各个分类和你的资料库，搜索随输随筛，安装前就能看到每个应用的下载大小，应用不适合你服务器的处理器时还会提醒你。",
      },
    },
    {
      icon: "packager",
      tag: {
        accent: true,
        text: {
          en: "800+ Apps",
          es: "Más de 800 apps",
          de: "Über 800 Apps",
          fr: "Plus de 800 apps",
          it: "Oltre 800 app",
          pt: "Mais de 800 apps",
          ru: "Более 800 приложений",
          uk: "Понад 800 застосунків",
          ja: "800 以上のアプリ",
          ko: "800개 이상의 앱",
          zh: "800+ 款应用",
        },
      },
      image: "community-stores.webp",
      title: {
        en: "Over 800 apps with six community stores",
        es: "Más de 800 apps con seis tiendas de la comunidad",
        de: "Über 800 Apps mit sechs Community-Stores",
        fr: "Plus de 800 apps avec six stores communautaires",
        it: "Oltre 800 app con sei store della community",
        pt: "Mais de 800 apps com seis lojas da comunidade",
        ru: "Более 800 приложений из шести магазинов сообщества",
        uk: "Понад 800 застосунків із шести крамниць спільноти",
        ja: "6 つのコミュニティストアで 800 以上のアプリ",
        ko: "여섯 개 커뮤니티 스토어로 800개 이상의 앱",
        zh: "六个社区商店，800 多款应用",
      },
      body: {
        en: "Packager got the App Store treatment, and Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore and Casa LinuxServer are one click away each, with a real progress bar while they download.",
        es: "Packager recibe el mismo trato que la App Store, y Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore y Casa LinuxServer están a un clic cada una, con una barra de progreso de verdad mientras se descargan.",
        de: "Packager bekommt das App-Store-Design, und Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore und Casa LinuxServer sind jeweils nur einen Klick entfernt, mit einem echten Fortschrittsbalken beim Herunterladen.",
        fr: "Packager reçoit le même traitement que l'App Store, et Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore et Casa LinuxServer sont chacun à un clic, avec une vraie barre de progression pendant le téléchargement.",
        it: "Packager riceve lo stesso trattamento dell'App Store, e Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore e Casa LinuxServer sono a un clic ciascuno, con una vera barra di avanzamento durante il download.",
        pt: "O Packager ganhou o mesmo tratamento da App Store, e Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore e Casa LinuxServer estão a um clique cada, com uma barra de progresso de verdade durante o download.",
        ru: "Packager получил оформление App Store, а Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore и Casa LinuxServer добавляются одним щелчком, с настоящим индикатором прогресса во время загрузки.",
        uk: "Packager отримав оформлення App Store, а Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore і Casa LinuxServer додаються одним клацанням, зі справжнім індикатором поступу під час завантаження.",
        ja: "Packager も App Store と同じ作りになり、Casa App Store、BigBearTechWorld、TMC Store、Zima App Store、Coolstore、Casa LinuxServer をそれぞれワンクリックで追加できます。ダウンロード中は本物のプログレスバーが表示されます。",
        ko: "Packager도 App Store와 같은 모습이 되었고, Casa App Store, BigBearTechWorld, TMC Store, Zima App Store, Coolstore, Casa LinuxServer를 각각 클릭 한 번으로 추가할 수 있습니다. 다운로드하는 동안에는 진짜 진행률 표시줄이 나옵니다.",
        zh: "Packager 也换上了 App Store 的样子，Casa App Store、BigBearTechWorld、TMC Store、Zima App Store、Coolstore 和 Casa LinuxServer 都只需点一下即可添加，下载时有真正的进度条。",
      },
    },
    {
      icon: "logs",
      tag: {
        text: {
          en: "Real-time logs, for real",
          es: "Logs en tiempo real, de verdad",
          de: "Echtzeit-Logs, wirklich echt",
          fr: "Des logs en temps réel, pour de vrai",
          it: "Log in tempo reale, sul serio",
          pt: "Logs em tempo real, de verdade",
          ru: "Логи в реальном времени, по-настоящему",
          uk: "Логи в реальному часі, по-справжньому",
          ja: "リアルタイムログ、ガチで",
          ko: "실시간 로그, 진짜로",
          zh: "实时日志，真·实时",
        },
      },
      image: "live-logs.webp",
      title: {
        en: "Live logs you can actually read",
        es: "Logs en vivo que por fin se pueden leer",
        de: "Live-Logs, die man wirklich lesen kann",
        fr: "Des journaux en direct qu'on peut enfin lire",
        it: "Log dal vivo che si possono finalmente leggere",
        pt: "Logs ao vivo que dá para ler de verdade",
        ru: "Живые логи, которые наконец можно читать",
        uk: "Живі журнали, які нарешті можна читати",
        ja: "ちゃんと読めるライブログ",
        ko: "제대로 읽을 수 있는 실시간 로그",
        zh: "真正能读的实时日志",
      },
      body: {
        en: "Always live, in your app's own colors, errors in red and warnings in amber, with search, filters and time ranges. Scroll up and the view stays put until you come back.",
        es: "Siempre en vivo, con los colores de tu app, errores en rojo y avisos en ámbar, con búsqueda, filtros y rangos de tiempo. Sube para leer algo y la vista se queda donde la dejaste hasta que vuelvas.",
        de: "Immer live, in den Farben deiner App, Fehler in Rot und Warnungen in Bernstein, mit Suche, Filtern und Zeiträumen. Scrolle nach oben und die Ansicht bleibt stehen, bis du zurückkommst.",
        fr: "Toujours en direct, aux couleurs de votre app, erreurs en rouge et avertissements en ambre, avec recherche, filtres et plages horaires. Remontez pour lire et la vue reste en place jusqu'à votre retour.",
        it: "Sempre dal vivo, con i colori della tua app, errori in rosso e avvisi in ambra, con ricerca, filtri e intervalli di tempo. Scorri in su e la vista resta ferma finché non torni.",
        pt: "Sempre ao vivo, com as cores do seu app, erros em vermelho e avisos em âmbar, com busca, filtros e intervalos de tempo. Role para cima e a visualização fica parada até você voltar.",
        ru: "Всегда в реальном времени, в цветах вашего приложения, ошибки красным, предупреждения янтарным, с поиском, фильтрами и выбором периода. Прокрутите вверх, и вид останется на месте, пока вы не вернётесь.",
        uk: "Завжди наживо, у кольорах вашого застосунку, помилки червоним, попередження бурштиновим, з пошуком, фільтрами й вибором періоду. Прокрутіть угору, і вигляд залишиться на місці, доки ви не повернетеся.",
        ja: "常にライブで、アプリ自身の色のまま、エラーは赤、警告は琥珀色。検索、フィルター、期間指定もできます。上にスクロールすれば、戻るまで表示はそのまま止まります。",
        ko: "항상 실시간으로, 앱 고유의 색 그대로, 오류는 빨간색, 경고는 호박색으로 보여 주며 검색, 필터, 기간 선택까지 됩니다. 위로 스크롤하면 돌아올 때까지 화면이 그대로 멈춰 있습니다.",
        zh: "始终实时，保留应用自己的颜色，错误标红、警告标琥珀色，支持搜索、筛选和时间范围。向上滚动时视图会停在原处，直到你回来。",
      },
    },
    {
      icon: "drive",
      tag: {
        text: {
          en: "Hello sir, security",
          es: "Buenas, caballero, seguridad",
          de: "Guten Tag, Security",
          fr: "Bonjour monsieur, sécurité",
          it: "Buongiorno signore, sicurezza",
          pt: "Olá, senhor, segurança",
          ru: "Здравствуйте, охрана",
          uk: "Добрий день, охорона",
          ja: "失礼します、セキュリティです",
          ko: "안녕하세요, 보안팀입니다",
          zh: "您好，我们是安保",
        },
      },
      image: "app-drive.webp",
      title: {
        en: "App Drive reaches folders outside HomeDock OS",
        es: "App Drive llega a carpetas fuera de HomeDock OS",
        de: "App Drive erreicht Ordner außerhalb von HomeDock OS",
        fr: "App Drive atteint les dossiers en dehors de HomeDock OS",
        it: "App Drive arriva alle cartelle fuori da HomeDock OS",
        pt: "O App Drive alcança pastas fora do HomeDock OS",
        ru: "App Drive добрался до папок за пределами HomeDock OS",
        uk: "App Drive дістався тек поза HomeDock OS",
        ja: "App Drive が HomeDock OS の外のフォルダーにも届きます",
        ko: "App Drive가 HomeDock OS 밖의 폴더까지 닿습니다",
        zh: "App Drive 可以访问 HomeDock OS 之外的文件夹了",
      },
      body: {
        en: "Folders your apps mount from the host show up locked and ask for your password before opening, one app at a time. Dependencies are listed too, and it finally works on Windows.",
        es: "Las carpetas que tus apps montan desde el host aparecen bloqueadas y piden tu contraseña antes de abrirse, app por app. También salen las dependencias, y por fin funciona en Windows.",
        de: "Ordner, die deine Apps vom Host einbinden, erscheinen gesperrt und fragen vor dem Öffnen nach deinem Passwort, App für App. Abhängigkeiten werden ebenfalls angezeigt, und unter Windows funktioniert es endlich.",
        fr: "Les dossiers que vos apps montent depuis l'hôte apparaissent verrouillés et demandent votre mot de passe avant de s'ouvrir, app par app. Les dépendances sont listées aussi, et ça marche enfin sous Windows.",
        it: "Le cartelle che le tue app montano dall'host compaiono bloccate e chiedono la password prima di aprirsi, un'app alla volta. Ci sono anche le dipendenze, e finalmente funziona su Windows.",
        pt: "As pastas que os seus apps montam do host aparecem bloqueadas e pedem a sua senha antes de abrir, um app de cada vez. As dependências também aparecem, e finalmente funciona no Windows.",
        ru: "Папки, которые приложения подключают с хоста, отображаются заблокированными и перед открытием спрашивают пароль, для каждого приложения отдельно. Зависимости тоже видны, и наконец всё работает в Windows.",
        uk: "Теки, які застосунки підключають із хоста, показуються заблокованими й перед відкриттям питають пароль, для кожного застосунку окремо. Залежності теж видно, і нарешті все працює у Windows.",
        ja: "アプリがホストからマウントしたフォルダーはロックされた状態で表示され、開く前にアプリごとにパスワードを求めます。依存関係も一覧に並び、ようやく Windows でも動くようになりました。",
        ko: "앱이 호스트에서 마운트한 폴더는 잠긴 채로 표시되고, 열기 전에 앱별로 비밀번호를 묻습니다. 의존성도 함께 보이며, 드디어 Windows에서도 동작합니다.",
        zh: "应用从宿主机挂载的文件夹会以锁定状态显示，打开前按应用逐个要求输入密码。依赖也会列出来，而且终于能在 Windows 上用了。",
      },
    },
    {
      icon: "office",
      tag: {
        text: {
          en: "Meant to be Enterprise. Not anymore",
          es: "Iba a ser Enterprise. Ya no",
          de: "Sollte Enterprise sein. Jetzt nicht mehr",
          fr: "Prévu pour Enterprise. Plus maintenant",
          it: "Doveva essere Enterprise. Non più",
          pt: "Era para ser Enterprise. Não é mais",
          ru: "Должно было быть в Enterprise. Уже нет",
          uk: "Мало бути в Enterprise. Вже ні",
          ja: "Enterprise 限定の予定でした。もう違います",
          ko: "Enterprise 전용이 될 뻔했지만, 이제 아닙니다",
          zh: "原本是 Enterprise 专属，现在不是了",
        },
      },
      image: "sheets-writer.webp",
      title: {
        en: "Sheets and Writer open your documents",
        es: "Sheets y Writer abren tus documentos",
        de: "Sheets und Writer öffnen deine Dokumente",
        fr: "Sheets et Writer ouvrent vos documents",
        it: "Sheets e Writer aprono i tuoi documenti",
        pt: "Sheets e Writer abrem os seus documentos",
        ru: "Sheets и Writer открывают ваши документы",
        uk: "Sheets і Writer відкривають ваші документи",
        ja: "Sheets と Writer で文書を開けます",
        ko: "Sheets와 Writer로 문서를 엽니다",
        zh: "Sheets 和 Writer 打开你的文档",
      },
      body: {
        en: "Double-click an .xlsx or a .docx and edit it right there: formulas, formatting, tables and images. Ctrl+S saves it back to the same file, wherever it lives.",
        es: "Haz doble clic en un .xlsx o un .docx y edítalo ahí mismo: fórmulas, formato, tablas e imágenes. Ctrl+S lo guarda en el mismo archivo, esté donde esté.",
        de: "Doppelklicke auf eine .xlsx oder .docx und bearbeite sie direkt: Formeln, Formatierung, Tabellen und Bilder. Strg+S speichert zurück in dieselbe Datei, egal wo sie liegt.",
        fr: "Double-cliquez sur un .xlsx ou un .docx et modifiez-le sur place : formules, mise en forme, tableaux et images. Ctrl+S l'enregistre dans le même fichier, où qu'il se trouve.",
        it: "Fai doppio clic su un .xlsx o un .docx e modificalo lì: formule, formattazione, tabelle e immagini. Ctrl+S lo salva nello stesso file, ovunque si trovi.",
        pt: "Clique duas vezes num .xlsx ou num .docx e edite ali mesmo: fórmulas, formatação, tabelas e imagens. Ctrl+S salva no mesmo arquivo, esteja onde estiver.",
        ru: "Дважды щёлкните по .xlsx или .docx и редактируйте прямо там: формулы, форматирование, таблицы и изображения. Ctrl+S сохраняет в тот же файл, где бы он ни лежал.",
        uk: "Двічі клацніть .xlsx або .docx і редагуйте просто там: формули, форматування, таблиці й зображення. Ctrl+S зберігає в той самий файл, хоч би де він був.",
        ja: ".xlsx や .docx をダブルクリックすれば、その場で編集できます。数式、書式、表、画像まで。Ctrl+S で、どこにあっても同じファイルに保存されます。",
        ko: ".xlsx나 .docx를 더블클릭하면 바로 그 자리에서 편집할 수 있습니다. 수식, 서식, 표, 이미지까지. Ctrl+S를 누르면 어디에 있든 같은 파일에 저장됩니다.",
        zh: "双击 .xlsx 或 .docx 就能直接编辑：公式、格式、表格和图片都行。按 Ctrl+S 会存回原来的文件，不管它放在哪里。",
      },
    },
    {
      icon: "images",
      tag: {
        text: {
          en: "Suuuuperfast!",
          es: "¡Suuuuperrápido!",
          de: "Suuuuperschnell!",
          fr: "Suuuuper rapide !",
          it: "Suuuuper veloce!",
          pt: "Suuuuper-rápido!",
          ru: "Суууупербыстро!",
          uk: "Суууупершвидко!",
          ja: "ちょーーーー速い！",
          ko: "초오오오오고속!",
          zh: "超超超超级快！",
        },
      },
      image: "thumbnails.webp",
      title: {
        en: "Thumbnails for your pictures",
        es: "Miniaturas para tus fotos",
        de: "Vorschaubilder für deine Fotos",
        fr: "Des miniatures pour vos photos",
        it: "Miniature per le tue foto",
        pt: "Miniaturas para as suas fotos",
        ru: "Миниатюры для ваших фотографий",
        uk: "Мініатюри для ваших фотографій",
        ja: "写真のサムネイル",
        ko: "사진 썸네일",
        zh: "为你的图片生成缩略图",
      },
      body: {
        en: "The File Explorer shows what is inside each image, camera RAW and Photoshop files included, and the Image Viewer now opens the formats your browser can't.",
        es: "El Explorador de Archivos enseña lo que hay dentro de cada imagen, RAW de cámara y archivos de Photoshop incluidos, y el Visor de Imágenes ya abre los formatos que tu navegador no sabe abrir.",
        de: "Der Datei-Explorer zeigt, was in jedem Bild steckt, Kamera-RAW und Photoshop-Dateien inklusive, und der Bildbetrachter öffnet jetzt die Formate, die dein Browser nicht kann.",
        fr: "L'Explorateur de fichiers montre le contenu de chaque image, RAW d'appareil photo et fichiers Photoshop compris, et la Visionneuse d'images ouvre désormais les formats que votre navigateur ne sait pas lire.",
        it: "Esplora File mostra cosa c'è dentro ogni immagine, RAW delle fotocamere e file Photoshop compresi, e il Visualizzatore immagini ora apre i formati che il tuo browser non sa aprire.",
        pt: "O Explorador de arquivos mostra o que há dentro de cada imagem, RAW de câmera e arquivos do Photoshop incluídos, e o Visualizador de imagens agora abre os formatos que o seu navegador não abre.",
        ru: "Проводник показывает, что внутри каждого изображения, включая RAW с камер и файлы Photoshop, а Просмотр изображений теперь открывает форматы, с которыми не справляется браузер.",
        uk: "Провідник файлів показує, що всередині кожного зображення, включно з RAW із камер і файлами Photoshop, а Переглядач зображень тепер відкриває формати, з якими не впорається браузер.",
        ja: "ファイルエクスプローラーが、カメラの RAW や Photoshop ファイルも含めて各画像の中身を表示し、画像ビューアーはブラウザーが開けない形式も開けるようになりました。",
        ko: "파일 탐색기가 카메라 RAW와 Photoshop 파일까지 각 이미지의 내용을 보여 주고, 이미지 뷰어는 이제 브라우저가 열지 못하는 형식도 엽니다.",
        zh: "文件浏览器会显示每张图片的内容，包括相机 RAW 和 Photoshop 文件，图片查看器现在也能打开浏览器打不开的格式。",
      },
    },
    {
      icon: "search",
      tag: {
        text: {
          en: "Find stuff, instantly",
          es: "Encuéntralo todo al instante",
          de: "Alles finden, sofort",
          fr: "Tout trouver, instantanément",
          it: "Trova tutto, all'istante",
          pt: "Encontre tudo, na hora",
          ru: "Найдите всё мгновенно",
          uk: "Знайдіть усе миттєво",
          ja: "なんでも、すぐに見つかる",
          ko: "무엇이든, 바로 찾기",
          zh: "一搜即得",
        },
      },
      image: "start-finder.webp",
      title: {
        en: "A rebuilt Start menu and Finder",
        es: "Menú Inicio y Finder rehechos",
        de: "Startmenü und Finder neu gebaut",
        fr: "Un menu Démarrer et un Finder refaits",
        it: "Menu Start e Finder rifatti da capo",
        pt: "Menu Iniciar e Finder refeitos",
        ru: "Новые меню «Пуск» и Finder",
        uk: "Нові меню «Пуск» і Finder",
        ja: "作り直したスタートメニューと Finder",
        ko: "새로 만든 시작 메뉴와 Finder",
        zh: "重做的开始菜单和 Finder",
      },
      body: {
        en: "Type to find apps and files, pin what you use and get back to what you opened this morning. Finder previews the selection and offers the button you actually wanted.",
        es: "Escribe para encontrar apps y archivos, ancla lo que usas y vuelve a lo que abriste esta mañana. Finder previsualiza lo seleccionado y te ofrece justo el botón que buscabas.",
        de: "Tippe, um Apps und Dateien zu finden, hefte an, was du nutzt, und kehre zu dem zurück, was du heute Morgen geöffnet hast. Finder zeigt eine Vorschau der Auswahl und genau den Knopf, den du wolltest.",
        fr: "Tapez pour trouver apps et fichiers, épinglez ce que vous utilisez et revenez à ce que vous avez ouvert ce matin. Finder prévisualise la sélection et propose le bouton que vous cherchiez.",
        it: "Scrivi per trovare app e file, fissa quello che usi e torna a ciò che hai aperto stamattina. Finder mostra un'anteprima della selezione e ti offre proprio il pulsante che volevi.",
        pt: "Digite para encontrar apps e arquivos, fixe o que você usa e volte ao que abriu hoje de manhã. O Finder mostra uma prévia da seleção e oferece o botão que você queria.",
        ru: "Начните печатать, чтобы найти приложения и файлы, закрепите то, чем пользуетесь, и вернитесь к тому, что открывали утром. Finder показывает предпросмотр выбранного и ту самую нужную кнопку.",
        uk: "Почніть друкувати, щоб знайти застосунки й файли, закріпіть те, чим користуєтеся, і поверніться до того, що відкривали зранку. Finder показує попередній перегляд вибраного і ту саму потрібну кнопку.",
        ja: "入力するだけでアプリとファイルが見つかり、よく使うものはピン留めでき、今朝開いたものにもすぐ戻れます。Finder は選択中の項目をプレビューし、欲しかったボタンを差し出します。",
        ko: "입력하면 앱과 파일이 바로 찾아지고, 자주 쓰는 것은 고정하고, 오늘 아침에 열었던 것으로 바로 돌아갈 수 있습니다. Finder는 선택한 항목을 미리 보여 주고 원하던 버튼을 내밉니다.",
        zh: "输入即可找到应用和文件，把常用的固定下来，还能回到今天早上打开过的东西。Finder 会预览选中的内容，并给出你真正想要的那个按钮。",
      },
    },
    {
      icon: "games",
      tag: {
        accent: true,
        text: {
          en: "Tofu for selfhosters",
          es: "Tofu para selfhosters",
          de: "Tofu für Selfhoster",
          fr: "Du tofu pour les selfhosters",
          it: "Tofu per selfhoster",
          pt: "Tofu para selfhosters",
          ru: "Тофу для селфхостеров",
          uk: "Тофу для селфхостерів",
          ja: "セルフホスターのための豆腐",
          ko: "셀프호스터를 위한 두부",
          zh: "给自托管玩家的豆腐",
        },
      },
      image: "games.webp",
      title: {
        en: "Our first games",
        es: "Nuestros primeros juegos",
        de: "Unsere ersten Spiele",
        fr: "Nos premiers jeux",
        it: "I nostri primi giochi",
        pt: "Os nossos primeiros jogos",
        ru: "Наши первые игры",
        uk: "Наші перші ігри",
        ja: "初めてのゲーム",
        ko: "첫 번째 게임들",
        zh: "我们的第一批游戏",
      },
      body: {
        en: "Neon Rush, an endless synthwave racer, and Packet Snake, the classic on a neon grid. Both feed on your installed apps, and your best score follows your account.",
        es: "Neon Rush, una carrera sin fin por una autopista synthwave, y Packet Snake, el clásico sobre una rejilla de neón. Los dos se alimentan de tus apps instaladas, y tu récord te sigue en tu cuenta.",
        de: "Neon Rush, ein endloses Synthwave-Rennen, und Packet Snake, der Klassiker auf einem Neon-Raster. Beide ernähren sich von deinen installierten Apps, und dein Rekord folgt deinem Konto.",
        fr: "Neon Rush, une course sans fin sur une autoroute synthwave, et Packet Snake, le classique sur une grille néon. Tous deux se nourrissent de vos apps installées, et votre record suit votre compte.",
        it: "Neon Rush, una corsa infinita su un'autostrada synthwave, e Packet Snake, il classico su una griglia al neon. Entrambi si nutrono delle tue app installate, e il tuo record segue il tuo account.",
        pt: "Neon Rush, uma corrida sem fim numa estrada synthwave, e Packet Snake, o clássico numa grade de neon. Os dois se alimentam dos seus apps instalados, e o seu recorde acompanha a sua conta.",
        ru: "Neon Rush, бесконечная гонка по синтвейв-трассе, и Packet Snake, классика на неоновой сетке. Обе питаются вашими установленными приложениями, а рекорд сохраняется в учётной записи.",
        uk: "Neon Rush, нескінченні перегони синтвейв-трасою, і Packet Snake, класика на неоновій сітці. Обидві живляться вашими встановленими застосунками, а рекорд зберігається в обліковому записі.",
        ja: "シンセウェイヴのハイウェイを走り続ける Neon Rush と、ネオンのグリッドで遊ぶ定番の Packet Snake。どちらもインストール済みのアプリを糧にし、ベストスコアはアカウントについてきます。",
        ko: "신스웨이브 고속도로를 끝없이 달리는 Neon Rush와 네온 그리드 위의 고전 Packet Snake. 둘 다 설치된 앱을 먹고 자라며, 최고 기록은 계정을 따라다닙니다.",
        zh: "Neon Rush，一场在合成波公路上永不停歇的竞速；Packet Snake，霓虹网格上的经典贪吃蛇。两者都以你安装的应用为食，最高分会跟着你的账户走。",
      },
    },
    {
      icon: "palette",
      tag: { key: "Improved" },
      image: "fresh-look.webp",
      title: {
        en: "A fresh coat of paint",
        es: "Una mano de pintura",
        de: "Ein frischer Anstrich",
        fr: "Un coup de peinture neuf",
        it: "Una mano di vernice fresca",
        pt: "Uma demão de tinta nova",
        ru: "Свежий слой краски",
        uk: "Свіжий шар фарби",
        ja: "装いも新たに",
        ko: "새로 칠한 외관",
        zh: "焕然一新的外观",
      },
      body: {
        en: "Proper app icons, folders that look like folders, files colored by type, and a 3D logo on the sign-in screen that leans towards your mouse.",
        es: "Iconos de app como es debido, carpetas que parecen carpetas, archivos coloreados por tipo y un logo en 3D en la pantalla de inicio de sesión que se inclina hacia tu ratón.",
        de: "Richtige App-Icons, Ordner, die wie Ordner aussehen, Dateien nach Typ eingefärbt und ein 3D-Logo auf dem Anmeldebildschirm, das sich zu deiner Maus neigt.",
        fr: "De vraies icônes d'app, des dossiers qui ressemblent à des dossiers, des fichiers colorés selon leur type et un logo 3D sur l'écran de connexion qui se penche vers votre souris.",
        it: "Icone delle app come si deve, cartelle che sembrano cartelle, file colorati per tipo e un logo 3D nella schermata di accesso che si inclina verso il tuo mouse.",
        pt: "Ícones de app decentes, pastas com cara de pasta, arquivos coloridos por tipo e um logo em 3D na tela de login que se inclina na direção do seu mouse.",
        ru: "Настоящие значки приложений, папки, похожие на папки, файлы с цветом по типу и 3D-логотип на экране входа, который наклоняется к вашей мыши.",
        uk: "Справжні значки застосунків, теки, схожі на теки, файли з кольором за типом і 3D-логотип на екрані входу, що нахиляється до вашої миші.",
        ja: "ちゃんとしたアプリアイコン、フォルダーらしいフォルダー、種類ごとに色分けされたファイル、そしてマウスの方へ傾くサインイン画面の 3D ロゴ。",
        ko: "제대로 된 앱 아이콘, 폴더다운 폴더, 종류별로 색이 입혀진 파일, 그리고 마우스 쪽으로 기우는 로그인 화면의 3D 로고.",
        zh: "像样的应用图标、看起来像文件夹的文件夹、按类型着色的文件，以及登录界面上会朝鼠标倾斜的 3D 标志。",
      },
    },
    {
      icon: "music",
      tag: {
        text: {
          en: "Just because. Period.",
          es: "Porque sí, punto",
          de: "Einfach so. Punkt.",
          fr: "Parce que. Point.",
          it: "Perché sì, punto",
          pt: "Porque sim, e ponto",
          ru: "Потому что. Точка.",
          uk: "Бо так. Крапка.",
          ja: "なんとなく。以上。",
          ko: "그냥요. 끝.",
          zh: "就是想，没有为什么",
        },
      },
      image: "media-player.webp",
      title: {
        en: "Music you can see",
        es: "Música que se ve",
        de: "Musik, die man sieht",
        fr: "La musique, en relief",
        it: "Musica da vedere",
        pt: "Música que dá para ver",
        ru: "Музыку теперь видно",
        uk: "Музику тепер видно",
        ja: "目に見える音楽",
        ko: "눈으로 보는 음악",
        zh: "看得见的音乐",
      },
      body: {
        en: "The Media Player's spectrum is now a 3D landscape where every moment of the song leaves a ridge drifting into the distance, and the album art pulses with every beat.",
        es: "El espectro del reproductor ahora es un paisaje en 3D donde cada instante de la canción deja una cresta que se aleja en la distancia, y la carátula late con cada golpe de bombo.",
        de: "Das Spektrum des Media Players ist jetzt eine 3D-Landschaft, in der jeder Moment des Songs einen Kamm hinterlässt, der in die Ferne zieht, und das Albumcover pulsiert mit jedem Beat.",
        fr: "Le spectre du lecteur multimédia est désormais un paysage en 3D où chaque instant du morceau laisse une crête qui s'éloigne au loin, et la pochette bat au rythme de chaque temps.",
        it: "Lo spettro del lettore multimediale ora è un paesaggio in 3D in cui ogni istante del brano lascia una cresta che si allontana, e la copertina pulsa a ogni battito.",
        pt: "O espectro do reprodutor agora é uma paisagem em 3D em que cada momento da música deixa uma crista que some ao longe, e a capa do álbum pulsa a cada batida.",
        ru: "Спектр медиаплеера стал 3D-пейзажем: каждый момент песни оставляет гребень, уходящий вдаль, а обложка альбома пульсирует в такт каждому удару.",
        uk: "Спектр медіаплеєра став 3D-краєвидом: кожна мить пісні залишає гребінь, що відпливає вдалину, а обкладинка альбому пульсує в такт кожному удару.",
        ja: "メディアプレーヤーのスペクトラムは 3D の風景になりました。曲の一瞬一瞬が尾根となって遠くへ流れていき、アルバムアートはビートに合わせて脈打ちます。",
        ko: "미디어 플레이어의 스펙트럼이 이제 3D 풍경이 되었습니다. 곡의 매 순간이 능선을 남기며 멀리 흘러가고, 앨범 아트는 비트마다 고동칩니다.",
        zh: "媒体播放器的频谱现在是一片 3D 地形，歌曲的每一刻都会留下一道山脊向远方流去，专辑封面也会随着每一拍跳动。",
      },
    },
    {
      icon: "devices",
      title: {
        en: "Your desktop follows you",
        es: "Tu escritorio te sigue",
        de: "Dein Schreibtisch folgt dir",
        fr: "Votre bureau vous suit",
        it: "La tua scrivania ti segue",
        pt: "A sua área de trabalho segue você",
        ru: "Рабочий стол следует за вами",
        uk: "Стільниця йде за вами",
        ja: "デスクトップがついてきます",
        ko: "바탕화면이 따라옵니다",
        zh: "你的桌面会跟着你",
      },
      body: {
        en: "Folders, widgets and pinned apps are saved to your account, and each device keeps its own layout, so tidying up your laptop never scrambles your big monitor.",
        es: "Las carpetas, los widgets y las apps ancladas se guardan en tu cuenta, y cada dispositivo conserva su propia distribución, así que ordenar el portátil nunca te desordena el monitor grande.",
        de: "Ordner, Widgets und angeheftete Apps werden in deinem Konto gespeichert, und jedes Gerät behält sein eigenes Layout, sodass Aufräumen am Laptop nie deinen großen Monitor durcheinanderbringt.",
        fr: "Dossiers, widgets et apps épinglées sont enregistrés dans votre compte, et chaque appareil garde sa propre disposition : ranger votre portable ne met jamais le bazar sur votre grand écran.",
        it: "Cartelle, widget e app fissate vengono salvati nel tuo account, e ogni dispositivo mantiene la propria disposizione, così riordinare il portatile non scombina mai il monitor grande.",
        pt: "Pastas, widgets e apps fixados ficam salvos na sua conta, e cada dispositivo mantém o próprio layout, então arrumar o notebook nunca bagunça o monitor grande.",
        ru: "Папки, виджеты и закреплённые приложения сохраняются в вашей учётной записи, а у каждого устройства своя раскладка, так что порядок на ноутбуке никогда не перемешает большой монитор.",
        uk: "Теки, віджети й закріплені застосунки зберігаються у вашому обліковому записі, а кожен пристрій має власне розташування, тож лад на ноутбуці ніколи не переплутає великий монітор.",
        ja: "フォルダー、ウィジェット、ピン留めしたアプリはアカウントに保存され、デバイスごとに独自の配置を保ちます。ノートパソコンを片付けても、大きなモニターが散らかることはありません。",
        ko: "폴더, 위젯, 고정한 앱은 계정에 저장되고 기기마다 자기 배치를 유지합니다. 노트북을 정리해도 큰 모니터가 흐트러지지 않습니다.",
        zh: "文件夹、小组件和固定的应用都会保存到你的账户，每台设备保留自己的布局，所以整理笔记本不会把大显示器弄乱。",
      },
    },
    {
      icon: "next",
      title: {
        en: "And this is just the beginning",
        es: "Y esto es solo el principio",
        de: "Und das ist erst der Anfang",
        fr: "Et ce n'est que le début",
        it: "E questo è solo l'inizio",
        pt: "E isso é só o começo",
        ru: "И это только начало",
        uk: "І це лише початок",
        ja: "そして、これはまだ始まりにすぎません",
        ko: "그리고 이건 시작일 뿐입니다",
        zh: "而这只是开始",
      },
      body: {
        en: "On top of countless bug fixes and UI/UX refinements. Much of this was meant for 2.4, but we split the release in two to make sure the built-in reverse proxy was ready for production. It is. HomeDock OS is getting close to the shape we always had in mind, and soon the community will help shape it too: native Python + Vue 3 modules are on the way, so any developer can build native apps for HomeDock OS, just like we build our Enterprise modules.",
        es: "Además de una infinidad de correcciones y mejoras de diseño y experiencia de uso. Buena parte de esto iba a llegar con la 2.4, pero preferimos partir el lanzamiento en dos para asegurarnos de que el proxy inverso integrado estaba listo para producción. Lo está. HomeDock OS se acerca a la forma que siempre imaginamos, y pronto la comunidad también podrá darle forma: llegan los módulos nativos en Python + Vue 3, para que cualquier desarrollador pueda crear apps nativas para HomeDock OS, igual que hacemos nosotros con los módulos Enterprise.",
        de: "Dazu kommen unzählige Fehlerbehebungen und Verbesserungen an Design und Bedienung. Vieles davon war schon für 2.4 geplant, aber wir haben das Release lieber zweigeteilt, um sicherzugehen, dass der integrierte Reverse Proxy bereit für den Produktiveinsatz ist. Das ist er. HomeDock OS nähert sich der Form, die wir uns immer vorgestellt haben, und bald kann auch die Community es mitgestalten: Native Module mit Python + Vue 3 sind unterwegs, damit jeder Entwickler native Apps für HomeDock OS bauen kann, genau wie wir unsere Enterprise-Module.",
        fr: "Sans compter une foule de corrections et d'améliorations de design et d'ergonomie. Une bonne partie de tout cela devait arriver avec la 2.4, mais nous avons préféré couper la version en deux pour nous assurer que le reverse proxy intégré était prêt pour la production. Il l'est. HomeDock OS se rapproche de la forme que nous avons toujours imaginée, et bientôt la communauté pourra elle aussi la façonner : les modules natifs Python + Vue 3 arrivent, pour que n'importe quel développeur puisse créer des apps natives pour HomeDock OS, exactement comme nous le faisons avec les modules Enterprise.",
        it: "Oltre a un'infinità di correzioni e miglioramenti di design ed esperienza d'uso. Gran parte di tutto questo doveva arrivare con la 2.4, ma abbiamo preferito dividere il rilascio in due per assicurarci che il reverse proxy integrato fosse pronto per la produzione. Lo è. HomeDock OS si sta avvicinando alla forma che abbiamo sempre immaginato, e presto anche la community potrà plasmarla: arrivano i moduli nativi Python + Vue 3, così qualsiasi sviluppatore potrà creare app native per HomeDock OS, proprio come facciamo noi con i moduli Enterprise.",
        pt: "Além de uma infinidade de correções e melhorias de design e usabilidade. Boa parte disso era para ter chegado na 2.4, mas preferimos dividir o lançamento em dois para garantir que o proxy reverso integrado estava pronto para produção. Está. O HomeDock OS está chegando perto da forma que sempre imaginamos, e em breve a comunidade também vai poder moldá-lo: os módulos nativos em Python + Vue 3 estão chegando, para que qualquer desenvolvedor possa criar apps nativos para o HomeDock OS, assim como fazemos com os módulos Enterprise.",
        ru: "А ещё огромное количество исправлений и улучшений дизайна и удобства. Многое из этого должно было выйти в 2.4, но мы решили разделить релиз на два, чтобы убедиться, что встроенный обратный прокси готов к работе в продакшене. Он готов. HomeDock OS приближается к той форме, которую мы всегда себе представляли, и скоро её сможет формировать и сообщество: на подходе нативные модули на Python + Vue 3, чтобы любой разработчик мог создавать нативные приложения для HomeDock OS, так же как мы делаем наши модули Enterprise.",
        uk: "А ще величезна кількість виправлень і покращень дизайну та зручності. Багато з цього мало вийти у 2.4, але ми вирішили розділити реліз на два, щоб переконатися, що вбудований зворотний проксі готовий до продакшену. Він готовий. HomeDock OS наближається до форми, яку ми завжди уявляли, і незабаром її зможе формувати й спільнота: на підході нативні модулі на Python + Vue 3, щоб будь-який розробник міг створювати нативні застосунки для HomeDock OS, так само як ми створюємо наші модулі Enterprise.",
        ja: "さらに、数え切れないほどのバグ修正と、デザインや使い心地の改善も。これらの多くは本来 2.4 に入る予定でしたが、内蔵リバースプロキシが本番運用に耐えられるかを確かめるため、リリースを 2 つに分けました。結果は、耐えられます。HomeDock OS は私たちが思い描いてきた姿に近づいており、まもなくコミュニティもその姿を形づくれるようになります。Python + Vue 3 によるネイティブモジュールが登場し、私たちが Enterprise モジュールを作るのと同じように、どの開発者も HomeDock OS のネイティブアプリを作れるようになります。",
        ko: "여기에 셀 수 없이 많은 버그 수정과 디자인·사용성 개선도 더해졌습니다. 이 중 상당수는 원래 2.4에 들어갈 예정이었지만, 내장 리버스 프록시가 프로덕션에 준비됐는지 확인하기 위해 릴리스를 둘로 나눴습니다. 준비됐습니다. HomeDock OS는 우리가 늘 그려 온 모습에 가까워지고 있고, 곧 커뮤니티도 그 모습을 함께 만들 수 있게 됩니다. Python + Vue 3 네이티브 모듈이 곧 나와서, 우리가 Enterprise 모듈을 만드는 것처럼 어떤 개발자든 HomeDock OS용 네이티브 앱을 만들 수 있게 됩니다.",
        zh: "此外还有数不清的错误修复，以及设计和使用体验上的改进。其中很多本该随 2.4 一起发布，但我们决定把这次发布拆成两部分，先确认内置反向代理已经可以用于生产环境。结论是：可以。HomeDock OS 正在接近我们一直设想的样子，而很快，社区也能一起塑造它：基于 Python + Vue 3 的原生模块即将到来，任何开发者都能为 HomeDock OS 开发原生应用，就像我们开发 Enterprise 模块一样。",
      },
    },
  ],
};

const release24: WhatsNewRelease = {
  id: "onscreen-apps",
  version: "2.4",
  scene: [
    { icon: "widget", color: "#8b5cf6" },
    { icon: "shortcut", color: "#f59e0b" },
    { icon: "proxy", color: "#0ea5e9" },
    { icon: "lock", color: "#16a34a" },
  ],
  title: {
    en: "OnScreen Apps, Shortcuts, Widgets and more",
    es: "OnScreen Apps, accesos directos, widgets y más",
    de: "OnScreen Apps, Verknüpfungen, Widgets und mehr",
    fr: "OnScreen Apps, raccourcis, widgets et plus encore",
    it: "OnScreen Apps, collegamenti, widget e altro",
    pt: "OnScreen Apps, atalhos, widgets e muito mais",
    ru: "OnScreen Apps, ярлыки, виджеты и не только",
    uk: "OnScreen Apps, ярлики, віджети та інше",
    ja: "OnScreen Apps、ショートカット、ウィジェット、ほか多数",
    ko: "OnScreen Apps, 바로가기, 위젯 등",
    zh: "OnScreen Apps、快捷方式、小组件，以及更多",
  },
  subtitle: {
    en: "Applications now live inside HomeDock OS, in real windows, behind real HTTPS certificates.",
    es: "Las aplicaciones ya viven dentro de HomeDock OS, en ventanas de verdad y tras certificados HTTPS de verdad.",
    de: "Anwendungen leben jetzt in HomeDock OS, in echten Fenstern und hinter echten HTTPS-Zertifikaten.",
    fr: "Les applications vivent désormais dans HomeDock OS, dans de vraies fenêtres et derrière de vrais certificats HTTPS.",
    it: "Le applicazioni ora vivono dentro HomeDock OS, in finestre vere e dietro veri certificati HTTPS.",
    pt: "Os aplicativos agora vivem dentro do HomeDock OS, em janelas de verdade e atrás de certificados HTTPS de verdade.",
    ru: "Приложения теперь живут внутри HomeDock OS, в настоящих окнах и за настоящими сертификатами HTTPS.",
    uk: "Застосунки тепер живуть усередині HomeDock OS, у справжніх вікнах і за справжніми сертифікатами HTTPS.",
    ja: "アプリは HomeDock OS の中で、本物のウィンドウと本物の HTTPS 証明書とともに動くようになりました。",
    ko: "이제 애플리케이션은 HomeDock OS 안에서, 진짜 창과 진짜 HTTPS 인증서와 함께 동작합니다.",
    zh: "应用现在住在 HomeDock OS 里面，拥有真正的窗口和真正的 HTTPS 证书。",
  },
  changelogUrl: "https://github.com/BansheeTech/HomeDockOS/blob/main/CHANGELOG.md",
  entries: [
    {
      icon: "window",
      tag: { label: "OnScreen Apps", accent: true },
      image: "onscreen-apps.webp",
      docsUrl: "https://docs.homedock.cloud/homedock-os/desktop/#onscreen-apps",
      title: {
        en: "Apps open inside HomeDock OS",
        es: "Las apps se abren dentro de HomeDock OS",
        de: "Apps öffnen sich in HomeDock OS",
        fr: "Les apps s'ouvrent dans HomeDock OS",
        it: "Le app si aprono dentro HomeDock OS",
        pt: "As apps abrem dentro do HomeDock OS",
        ru: "Приложения открываются внутри HomeDock OS",
        uk: "Застосунки відкриваються всередині HomeDock OS",
        ja: "アプリは HomeDock OS の中で開きます",
        ko: "앱이 HomeDock OS 안에서 열립니다",
        zh: "应用在 HomeDock OS 内部打开",
      },
      body: {
        en: "Every app gets its own address and opens in a real window instead of another tab. Sound keeps playing while you drag it, and downloads land where you told them to.",
        es: "Cada aplicación tiene su propia dirección y se abre en una ventana real, no en otra pestaña. El sonido sigue sonando mientras la arrastras y las descargas caen donde tú dijiste.",
        de: "Jede App bekommt ihre eigene Adresse und öffnet sich in einem echten Fenster statt in einem weiteren Tab. Der Ton läuft weiter, während du sie ziehst, und Downloads landen dort, wo du es gesagt hast.",
        fr: "Chaque application a sa propre adresse et s'ouvre dans une vraie fenêtre plutôt que dans un autre onglet. Le son continue pendant que vous la déplacez et les téléchargements arrivent là où vous l'avez demandé.",
        it: "Ogni applicazione ha il proprio indirizzo e si apre in una finestra vera invece che in un'altra scheda. L'audio continua mentre la trascini e i download finiscono dove hai detto tu.",
        pt: "Cada aplicativo tem o seu próprio endereço e abre em uma janela de verdade, não em outra aba. O som continua tocando enquanto você arrasta a janela, e os downloads vão parar onde você mandou.",
        ru: "У каждого приложения свой адрес, и оно открывается в настоящем окне, а не в новой вкладке. Звук продолжает играть, пока вы перетаскиваете окно, а загрузки попадают туда, куда вы сказали.",
        uk: "Кожен застосунок має власну адресу і відкривається у справжньому вікні, а не в новій вкладці. Звук не переривається, поки ви перетягуєте вікно, а завантаження потрапляють туди, куди ви сказали.",
        ja: "すべてのアプリが独自のアドレスを持ち、別のタブではなく本物のウィンドウで開きます。ドラッグ中も音は途切れず、ダウンロードは指定した場所に届きます。",
        ko: "모든 앱이 각자의 주소를 갖고 새 탭이 아니라 진짜 창에서 열립니다. 창을 끄는 동안에도 소리는 계속 나오고, 다운로드는 지정한 곳으로 저장됩니다.",
        zh: "每个应用都有自己的地址，并在真正的窗口中打开，而不是另开一个标签页。拖动时声音不会中断，下载也会落到你指定的位置。",
      },
    },
    {
      icon: "split",
      image: "side-by-side.webp",
      docsUrl: "https://docs.homedock.cloud/homedock-os/desktop/#quick-view",
      title: {
        en: "Two apps at once, side by side",
        es: "Dos apps a la vez, una al lado de la otra",
        de: "Zwei Apps gleichzeitig, nebeneinander",
        fr: "Deux apps à la fois, côte à côte",
        it: "Due app insieme, una accanto all'altra",
        pt: "Duas apps ao mesmo tempo, lado a lado",
        ru: "Два приложения сразу, бок о бок",
        uk: "Два застосунки водночас, поруч",
        ja: "2 つのアプリを並べて同時に",
        ko: "두 앱을 나란히 동시에",
        zh: "两个应用并排同时使用",
      },
      body: {
        en: "Resize them, stack them, work in one while the other keeps running. This is the part a browser tab was never going to give you.",
        es: "Cámbialas de tamaño, apílalas, trabaja en una mientras la otra sigue funcionando. Esto es lo que una pestaña del navegador nunca te iba a dar.",
        de: "Größe ändern, stapeln, in der einen arbeiten, während die andere weiterläuft. Genau das konnte ein Browser-Tab nie leisten.",
        fr: "Redimensionnez-les, empilez-les, travaillez dans l'une pendant que l'autre tourne. C'est précisément ce qu'un onglet de navigateur n'allait jamais vous offrir.",
        it: "Ridimensionale, impilale, lavora in una mentre l'altra continua a girare. È proprio quello che una scheda del browser non ti avrebbe mai dato.",
        pt: "Redimensione, empilhe, trabalhe em um enquanto o outro continua rodando. É justamente o que uma aba do navegador nunca ia te dar.",
        ru: "Меняйте размер, накладывайте друг на друга, работайте в одном, пока второе продолжает работать. Именно этого вкладка браузера никогда бы вам не дала.",
        uk: "Змінюйте розмір, складайте їх, працюйте в одному, поки інший далі працює. Саме цього вкладка браузера вам ніколи б не дала.",
        ja: "サイズを変え、重ね、片方を動かしたままもう片方で作業できます。ブラウザーのタブには決してできなかった部分です。",
        ko: "크기를 바꾸고, 겹치고, 하나에서 작업하는 동안 다른 하나는 계속 돌아갑니다. 브라우저 탭으로는 결코 얻을 수 없던 부분입니다.",
        zh: "调整大小、层叠摆放，在一个里工作的同时另一个照常运行。这正是浏览器标签页永远给不了你的部分。",
      },
    },
    {
      icon: "lock",
      tag: { label: "Let's Encrypt SSL", accent: true },
      image: "https-certificates.webp",
      docsUrl: "https://docs.homedock.cloud/setup/ssl-https/#automatic-certificates",
      title: {
        en: "Automatic HTTPS certificates",
        es: "Certificados HTTPS automáticos",
        de: "Automatische HTTPS-Zertifikate",
        fr: "Certificats HTTPS automatiques",
        it: "Certificati HTTPS automatici",
        pt: "Certificados HTTPS automáticos",
        ru: "Автоматические сертификаты HTTPS",
        uk: "Автоматичні сертифікати HTTPS",
        ja: "HTTPS 証明書を自動で取得",
        ko: "자동 HTTPS 인증서",
        zh: "自动 HTTPS 证书",
      },
      body: {
        en: "Pick your DNS provider, paste a token, and HomeDock OS obtains a real wildcard certificate for your domain and every app under it. No app ports to open anymore.",
        es: "Elige tu proveedor de DNS, pega un token y HomeDock OS obtiene un certificado wildcard real para tu dominio y para todas las apps que cuelgan de él. Ya no hay que abrir puertos por aplicación.",
        de: "Wähle deinen DNS-Anbieter, füge ein Token ein, und HomeDock OS holt ein echtes Wildcard-Zertifikat für deine Domain und jede App darunter. Keine App-Ports mehr, die geöffnet werden müssen.",
        fr: "Choisissez votre fournisseur DNS, collez un jeton, et HomeDock OS obtient un vrai certificat wildcard pour votre domaine et toutes les apps qui en dépendent. Plus aucun port d'application à ouvrir.",
        it: "Scegli il tuo provider DNS, incolla un token e HomeDock OS ottiene un vero certificato wildcard per il tuo dominio e per ogni app che ci sta sotto. Niente più porte da aprire per le app.",
        pt: "Escolha o seu provedor de DNS, cole um token e o HomeDock OS obtém um certificado wildcard de verdade para o seu domínio e para todos os aplicativos abaixo dele. Não há mais portas de aplicativo para abrir.",
        ru: "Выберите DNS-провайдера, вставьте токен, и HomeDock OS получит настоящий wildcard-сертификат для вашего домена и всех приложений под ним. Больше не нужно открывать порты для приложений.",
        uk: "Оберіть свого DNS-провайдера, вставте токен, і HomeDock OS отримає справжній wildcard-сертифікат для вашого домену та всіх застосунків під ним. Більше не треба відкривати порти для застосунків.",
        ja: "DNS プロバイダーを選んでトークンを貼るだけで、HomeDock OS がドメインとその下のすべてのアプリに有効な本物のワイルドカード証明書を取得します。アプリごとのポート開放はもう不要です。",
        ko: "DNS 공급자를 고르고 토큰을 붙여넣으면 HomeDock OS가 도메인과 그 아래 모든 앱을 위한 진짜 와일드카드 인증서를 받아옵니다. 이제 앱마다 포트를 열 필요가 없습니다.",
        zh: "选择你的 DNS 服务商，粘贴一个令牌，HomeDock OS 就会为你的域名及其下的每个应用取得真正的通配符证书。不必再为应用开放端口。",
      },
    },
    {
      icon: "proxy",
      docsUrl: "https://docs.homedock.cloud/homedock-os/desktop/#onscreen-apps",
      title: {
        en: "A reverse proxy you never have to install",
        es: "Un proxy inverso que no tienes que instalar",
        de: "Ein Reverse Proxy, den du nie installieren musst",
        fr: "Un reverse proxy que vous n'avez jamais à installer",
        it: "Un reverse proxy che non devi installare",
        pt: "Um proxy reverso que você nunca precisa instalar",
        ru: "Обратный прокси, который не нужно устанавливать",
        uk: "Зворотний проксі, який не треба встановлювати",
        ja: "インストール不要のリバースプロキシ",
        ko: "설치할 필요가 없는 리버스 프록시",
        zh: "一个你永远不用安装的反向代理",
      },
      body: {
        en: "Host-based routing built in, HTTPS in front of containers that only speak HTTP, and WebSockets proxied end to end. Installing an app is the whole setup.",
        es: "Enrutado por Host integrado, HTTPS por delante de contenedores que solo hablan HTTP y WebSockets pasados de extremo a extremo. Instalar una app es toda la configuración.",
        de: "Host-basiertes Routing eingebaut, HTTPS vor Containern, die nur HTTP sprechen, und WebSockets durchgereicht. Eine App zu installieren ist die gesamte Einrichtung.",
        fr: "Routage par Host intégré, HTTPS devant des conteneurs qui ne parlent que HTTP, et WebSockets relayés de bout en bout. Installer une app, c'est toute la configuration.",
        it: "Routing per Host integrato, HTTPS davanti a container che parlano solo HTTP e WebSocket inoltrati da un capo all'altro. Installare un'app è tutta la configurazione.",
        pt: "Roteamento por Host integrado, HTTPS na frente de contêineres que só falam HTTP e WebSockets encaminhados de ponta a ponta. Instalar um aplicativo é toda a configuração.",
        ru: "Встроенная маршрутизация по Host, HTTPS перед контейнерами, которые умеют только HTTP, и WebSocket, проброшенный насквозь. Установка приложения и есть вся настройка.",
        uk: "Вбудована маршрутизація за Host, HTTPS перед контейнерами, що знають лише HTTP, і WebSocket, проведений наскрізь. Встановити застосунок — це і є вся настройка.",
        ja: "Host ベースのルーティングを内蔵し、HTTP しか話さないコンテナの前に HTTPS を置き、WebSocket も端から端まで中継します。アプリを入れれば設定は終わりです。",
        ko: "Host 기반 라우팅이 기본 탑재되어 HTTP만 아는 컨테이너 앞에 HTTPS를 세우고, WebSocket도 끝까지 중계합니다. 앱을 설치하면 설정은 그것으로 끝입니다.",
        zh: "内置基于 Host 的路由，为只会说 HTTP 的容器套上 HTTPS，并端到端转发 WebSocket。装好应用，配置就已经完成了。",
      },
    },
    {
      icon: "widget",
      image: "widgets.webp",
      docsUrl: "https://docs.homedock.cloud/homedock-os/desktop/#widgets",
      title: {
        en: "Widgets on the desktop",
        es: "Widgets en el escritorio",
        de: "Widgets auf dem Schreibtisch",
        fr: "Des widgets sur le bureau",
        it: "Widget sulla scrivania",
        pt: "Widgets na área de trabalho",
        ru: "Виджеты на рабочем столе",
        uk: "Віджети на стільниці",
        ja: "デスクトップにウィジェット",
        ko: "바탕화면 위의 위젯",
        zh: "桌面上的小组件",
      },
      body: {
        en: "Clock, System, Storage, Notes, Network, Calendar, Media and Shortcut, anywhere on the grid. The wallpaper was not doing much anyway.",
        es: "Reloj, Sistema, Almacenamiento, Notas, Red, Calendario, Multimedia y Acceso directo, donde quieras de la rejilla. El fondo de pantalla tampoco hacía gran cosa.",
        de: "Uhr, System, Speicher, Notizen, Netzwerk, Kalender, Medien und Verknüpfung, überall im Raster. Das Hintergrundbild hatte ohnehin wenig zu tun.",
        fr: "Horloge, Système, Stockage, Notes, Réseau, Calendrier, Média et Raccourci, où vous voulez sur la grille. Le fond d'écran ne faisait pas grand-chose de toute façon.",
        it: "Orologio, Sistema, Archiviazione, Note, Rete, Calendario, Media e Collegamento, ovunque sulla griglia. Lo sfondo non stava facendo granché.",
        pt: "Relógio, Sistema, Armazenamento, Notas, Rede, Calendário, Mídia e Atalho, em qualquer lugar da grade. O papel de parede também não estava fazendo muita coisa.",
        ru: "Часы, Система, Хранилище, Заметки, Сеть, Календарь, Медиа и Ярлык, в любом месте сетки. Обои всё равно простаивали.",
        uk: "Годинник, Система, Сховище, Нотатки, Мережа, Календар, Медіа і Ярлик, будь-де на сітці. Шпалери все одно нічого не робили.",
        ja: "時計、システム、ストレージ、メモ、ネットワーク、カレンダー、メディア、ショートカットをグリッドの好きな場所へ。どうせ壁紙は暇そうでした。",
        ko: "시계, 시스템, 저장소, 메모, 네트워크, 캘린더, 미디어, 바로가기를 그리드 어디에나. 배경화면은 어차피 별로 하는 일이 없었습니다.",
        zh: "时钟、系统、存储、便签、网络、日历、媒体和快捷方式，放在网格上的任意位置。反正壁纸也没什么事做。",
      },
    },
    {
      icon: "shortcut",
      image: "shortcuts.webp",
      docsUrl: "https://docs.homedock.cloud/homedock-os/desktop/#desktop-shortcuts",
      title: {
        en: "Shortcuts to sites, files and folders",
        es: "Accesos directos a webs, archivos y carpetas",
        de: "Verknüpfungen zu Seiten, Dateien und Ordnern",
        fr: "Des raccourcis vers des sites, des fichiers et des dossiers",
        it: "Collegamenti a siti, file e cartelle",
        pt: "Atalhos para sites, arquivos e pastas",
        ru: "Ярлыки на сайты, файлы и папки",
        uk: "Ярлики на сайти, файли та теки",
        ja: "サイト、ファイル、フォルダーへのショートカット",
        ko: "사이트, 파일, 폴더 바로가기",
        zh: "指向网站、文件和文件夹的快捷方式",
      },
      body: {
        en: "Paste a URL, or right-click anything in File Explorer and add it to the Desktop. Nothing is ever copied: a shortcut is a pointer and weighs nothing.",
        es: "Pega una URL, o haz clic derecho en cualquier cosa del Explorador de Archivos y añádela al escritorio. Nunca se copia nada: un acceso directo es un puntero y no pesa.",
        de: "Füge eine URL ein oder klicke mit rechts auf etwas im Datei-Explorer und lege es auf den Schreibtisch. Nichts wird kopiert: eine Verknüpfung ist ein Zeiger und wiegt nichts.",
        fr: "Collez une URL, ou faites un clic droit sur n'importe quoi dans l'Explorateur de fichiers et ajoutez-le au bureau. Rien n'est jamais copié : un raccourci est un pointeur et ne pèse rien.",
        it: "Incolla un URL, oppure fai clic destro su qualsiasi cosa in Esplora File e aggiungila alla scrivania. Non viene mai copiato nulla: un collegamento è un puntatore e non pesa.",
        pt: "Cole uma URL, ou clique com o botão direito em qualquer coisa no Explorador de arquivos e adicione à área de trabalho. Nada é copiado: um atalho é um ponteiro e não pesa nada.",
        ru: "Вставьте ссылку или щёлкните правой кнопкой по чему угодно в Проводнике и добавьте это на рабочий стол. Ничего не копируется: ярлык — это указатель, он ничего не весит.",
        uk: "Вставте URL або клацніть правою кнопкою будь-що в Провіднику файлів і додайте це на стільницю. Нічого не копіюється: ярлик — це вказівник, він нічого не важить.",
        ja: "URL を貼り付けるか、ファイルエクスプローラーで右クリックしてデスクトップに追加するだけ。コピーは一切されません。ショートカットはポインターで、容量を取りません。",
        ko: "URL을 붙여넣거나 파일 탐색기에서 아무거나 마우스 오른쪽 버튼으로 눌러 바탕화면에 추가하세요. 아무것도 복사되지 않습니다. 바로가기는 포인터라 용량을 차지하지 않습니다.",
        zh: "粘贴一个网址，或在文件浏览器中右键点击任意内容并添加到桌面。不会复制任何东西：快捷方式只是一个指针，不占空间。",
      },
    },
    {
      icon: "quickview",
      image: "quick-view.webp",
      docsUrl: "https://docs.homedock.cloud/homedock-os/desktop/#quick-view",
      title: {
        en: "Quick View and screenshots",
        es: "Vista rápida y capturas de pantalla",
        de: "Schnellansicht und Screenshots",
        fr: "Aperçu rapide et captures d'écran",
        it: "Vista rapida e screenshot",
        pt: "Vista rápida e capturas de tela",
        ru: "Быстрый просмотр и снимки экрана",
        uk: "Швидкий перегляд і знімки екрана",
        ja: "クイックビューとスクリーンショット",
        ko: "빠른 보기와 스크린샷",
        zh: "快速查看与截图",
      },
      body: {
        en: "F3 spreads every open window into a grid and brings them back where they were. Screenshot captures what you actually see, apps included, straight into Photos.",
        es: "F3 despliega todas las ventanas abiertas en una rejilla y las devuelve a su sitio. La captura recoge lo que ves de verdad, apps incluidas, directa a Photos.",
        de: "F3 verteilt alle offenen Fenster in einem Raster und bringt sie zurück an ihren Platz. Der Screenshot nimmt auf, was du wirklich siehst, Apps inklusive, direkt nach Photos.",
        fr: "F3 étale toutes les fenêtres ouvertes en grille puis les remet à leur place. La capture prend ce que vous voyez vraiment, applications comprises, directement dans Photos.",
        it: "F3 dispone tutte le finestre aperte in una griglia e poi le rimette al loro posto. Lo screenshot cattura quello che vedi davvero, app comprese, dritto in Photos.",
        pt: "O F3 espalha todas as janelas abertas em uma grade e devolve cada uma ao seu lugar. A captura pega o que você realmente vê, aplicativos inclusive, direto para Photos.",
        ru: "F3 раскладывает все открытые окна в сетку и возвращает их на место. Снимок экрана захватывает то, что вы действительно видите, вместе с приложениями, прямо в Photos.",
        uk: "F3 розкладає всі відкриті вікна в сітку і повертає їх на місце. Знімок захоплює те, що ви справді бачите, разом із застосунками, одразу в Photos.",
        ja: "F3 で開いているウィンドウがグリッドに広がり、元の位置へ戻ります。スクリーンショットはアプリも含めて実際に見えているものを、そのまま Photos に保存します。",
        ko: "F3을 누르면 열린 창이 모두 그리드로 펼쳐졌다가 제자리로 돌아갑니다. 스크린샷은 앱까지 포함해 실제로 보이는 화면을 그대로 Photos에 저장합니다.",
        zh: "按 F3 让所有打开的窗口铺成网格，再各归各位。截图会捕捉你真正看到的画面，连同应用一起，直接存入 Photos。",
      },
    },
    {
      icon: "help",
      tag: { key: "Improved" },
      title: {
        en: "Every setting explains itself",
        es: "Cada ajuste se explica solo",
        de: "Jede Einstellung erklärt sich selbst",
        fr: "Chaque réglage s'explique tout seul",
        it: "Ogni impostazione si spiega da sola",
        pt: "Cada configuração se explica sozinha",
        ru: "Каждая настройка объясняет сама себя",
        uk: "Кожне налаштування пояснює себе саме",
        ja: "すべての設定が自分で説明します",
        ko: "모든 설정이 스스로를 설명합니다",
        zh: "每一项设置都会自我解释",
      },
      body: {
        en: "Twenty-one help notes across the five Settings panels: what each one does, what it costs you, and the edge case nobody warns you about.",
        es: "Veintiuna notas de ayuda repartidas por los cinco paneles de Ajustes: qué hace cada uno, qué te cuesta y el caso raro del que nadie te avisa.",
        de: "Einundzwanzig Hilfehinweise in den fünf Einstellungsbereichen: was jede Option tut, was sie kostet und der Sonderfall, vor dem dich niemand warnt.",
        fr: "Vingt et une notes d'aide réparties dans les cinq panneaux des Réglages : ce que fait chacun, ce qu'il coûte, et le cas particulier dont personne ne vous parle.",
        it: "Ventuno note di aiuto sparse nei cinque pannelli delle Impostazioni: cosa fa ciascuna, cosa ti costa e il caso limite di cui nessuno ti avverte.",
        pt: "Vinte e uma notas de ajuda pelos cinco painéis das Configurações: o que cada uma faz, o que ela custa e o caso raro sobre o qual ninguém te avisa.",
        ru: "Двадцать одна подсказка в пяти разделах настроек: что делает каждая опция, чего она стоит и тот самый случай, о котором никто не предупреждает.",
        uk: "Двадцять одна підказка в п'яти панелях налаштувань: що робить кожне, чого воно вартує і той окремий випадок, про який ніхто не попереджає.",
        ja: "設定の 5 つのパネルに 21 個のヘルプ。何をするのか、何と引き換えなのか、そして誰も教えてくれない例外まで。",
        ko: "설정의 다섯 개 패널에 걸친 스물한 개의 도움말: 무엇을 하는지, 무엇을 감수해야 하는지, 그리고 아무도 알려주지 않는 예외까지.",
        zh: "五个设置面板里共二十一条说明：它做什么、代价是什么，以及没人会提醒你的那个特殊情况。",
      },
    },
  ],
};

export const releases: WhatsNewRelease[] = [release26, release24];

export const latestRelease = releases[0];

export function missedReleases(seenId: string): WhatsNewRelease[] {
  if (!seenId) return [];

  const seenIndex = releases.findIndex((release) => release.id === seenId);
  return releases.slice(1, seenIndex === -1 ? releases.length : seenIndex);
}
