---
version: "2.1"
services:
  altus:
    image: lscr.io/linuxserver/altus:latest
    container_name: altus
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - KASM_SSL_CERT=/config/ssl/cert.crt
      - KASM_SSL_KEY=/config/ssl/cert.key
    volumes:
      - [[INSTALL_PATH]]/altus:/config
      - /DATA/SSLCerts/fullchain.pem:/config/ssl/cert.pem:ro
      - /DATA/SSLCerts/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 4963:3001
    shm_size: "1gb"
    restart: unless-stopped
