---
services:
  ardour:
    image: lscr.io/linuxserver/ardour:latest
    container_name: ardour
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE=Ardour
    volumes:
      - [[INSTALL_PATH]]/ardour:/config
      - /DATA/SSLCerts/fullchain.pem:/config/ssl/cert.pem:ro
      - /DATA/SSLCerts/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 3976:3001
    restart: unless-stopped
