---
services:
  audacity:
    image: lscr.io/linuxserver/audacity:latest
    container_name: audacity
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
      - TITLE=Audacity
    volumes:
      - [[INSTALL_PATH]]/audacity:/config
      - [[SSL_CERT_PATH]]/fullchain.pem:/config/ssl/cert.pem:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 3000:3001
    restart: unless-stopped
