---
version: "2.1"
services:
  bambustudio:
    image: lscr.io/linuxserver/bambustudio:latest
    container_name: bambustudio
    security_opt:
      - seccomp:unconfined
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
    volumes:
      - [[INSTALL_PATH]]/bambustudio:/config
      - /DATA/SSLCerts/fullchain.pem:/config/ssl/cert.pem:ro
      - /DATA/SSLCerts/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 9975:3001
    restart: unless-stopped
