---
services:
  blender:
    image: lscr.io/linuxserver/blender:latest
    container_name: blender
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - SUBFOLDER=/ #optional
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE=Blender
    volumes:
      - [[INSTALL_PATH]]/blender:/config
      - [[SSL_CERT_PATH]]/fullchain.pem:/config/ssl/cert.pem:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 3000:3001
    restart: unless-stopped
