---
services:
  budge:
    image: lscr.io/linuxserver/budge:latest
    container_name: budge
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/budge:/config
      - [[SSL_CERT_PATH]]/fullchain.pem:/config/keys/cert.crt:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/config/keys/cert.key:ro
    ports:
      - 11281:443
    restart: unless-stopped
