---
version: "2.1"
services:
  calligra:
    image: lscr.io/linuxserver/calligra:latest
    container_name: calligra
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - TITLE="Calligra"
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
    volumes:
      - [[INSTALL_PATH]]/calligra:/config
      - /DATA/SSLCerts/fullchain.pem:/config/ssl/cert.pem:ro
      - /DATA/SSLCerts/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 4414:3001
    restart: unless-stopped
