---
version: "2.1"
services:
  cura:
    image: lscr.io/linuxserver/cura:latest
    container_name: cura
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
      - TITLE=Cura
    volumes:
      - [[INSTALL_PATH]]/cura:/config
      - /DATA/SSLCerts/fullchain.pem:/config/ssl/cert.pem:ro
      - /DATA/SSLCerts/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 6466:3001
    restart: unless-stopped