---
services:
  davos:
    image: lscr.io/linuxserver/davos:latest
    container_name: davos
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/davos:/config
      - [[APP_MOUNT_POINT]]/davos/downloads:/download
      - /DATA/SSLCerts/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - /DATA/SSLCerts/privkey.pem:/etc/ssl/private/privkey.pem:ro
    ports:
      - 9090:8081
    entrypoint: ""
    command: >
      sh -c "
      echo '─────────────────────────────────────────────────────────────';
      echo '';
      echo '   Running official image from LinuxServer.io';
      echo '   Visit: https://www.linuxserver.io/';
      echo '';
      echo '   Modified at runtime for SSL support by HomeDock OS team';
      echo '   Visit too: https://www.homedock.cloud/';
      echo '';
      echo '─────────────────────────────────────────────────────────────';
      echo '';

      echo '[HomeDock OS] Installing runtime openssl...';
      apk add --no-cache openssl || true;
      echo '';
      echo '[HomeDock OS] Checking for SSL certificates...';

      if [ -f /etc/ssl/certs/fullchain.pem ] && [ -f /etc/ssl/private/privkey.pem ]; then
          echo '[HomeDock OS] SSL Certificates found. Generating PKCS12 keystore...';
          openssl pkcs12 -export \
              -in /etc/ssl/certs/fullchain.pem \
              -inkey /etc/ssl/private/privkey.pem \
              -out /config/keystore.p12 \
              -name davos \
              -password pass:homedockssl;
          echo '[HomeDock OS] Starting Davos in HTTPS mode on port 8081';
          java \
            -Dserver.port=8081 \
            -Dserver.ssl.enabled=true \
            -Dserver.ssl.key-store=/config/keystore.p12 \
            -Dserver.ssl.key-store-password=homedockssl \
            -Dserver.ssl.key-store-type=PKCS12 \
            -jar /app/davos/davos.jar;
      else
          echo '[HomeDock OS] SSL Certificates NOT found. Launching HTTP fallback...';
          java -jar /app/davos/davos.jar;
      fi
      "
    restart: unless-stopped