---
services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: filebrowser
    restart: unless-stopped
    ports:
      - 8765:80
    user: "0:0"
    working_dir: /config
    entrypoint: ["/bin/sh", "-c"]
    volumes:
      - [[INSTALL_PATH]]/filebrowser:/config
      - [[APP_MOUNT_POINT]]/filebrowser:/srv
      - [[SSL_CERT_PATH]]/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/etc/ssl/private/privkey.pem:ro
    environment:
      - FB_CERT=/etc/ssl/certs/fullchain.pem
      - FB_KEY=/etc/ssl/private/privkey.pem
      - FB_PORT=80
      - FBUSER=[[HD_USER_NAME]]
      - FBPASS=[[HD_PASSWORD]]
    command: >
             "filebrowser config init || true &&
             filebrowser config set --root /srv &&
             filebrowser users ls | grep $$FBUSER || filebrowser users add $$FBUSER $$FBPASS --perm.admin &&
             filebrowser -a 0.0.0.0 -p 80"
