---
services:
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: firefox
    security_opt:
      - seccomp:unconfined #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
      - FIREFOX_CLI=https://www.homedock.cloud/
    volumes:
      - [[INSTALL_PATH]]/firefox:/config
      - [[SSL_CERT_PATH]]/fullchain.pem:/config/ssl/cert.pem:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 3000:3001
    shm_size: "1gb"
    restart: unless-stopped
