---
services:
  navidrome:
    image: deluan/navidrome:latest
    container_name: navidrome
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info
      ND_BASEURL: ""
    volumes:
      - [[INSTALL_PATH]]/navidrome:/data
      - [[APP_MOUNT_POINT]]/navidrome/music:/music:ro
      - [[SSL_CERT_PATH]]:/etc/ssl/custom:ro
    command: "--tlscert=/etc/ssl/custom/fullchain.pem --tlskey=/etc/ssl/custom/privkey.pem"
