---
services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/nextcloud:/config
      - [[APP_MOUNT_POINT]]/nextcloud/data:/data
      - [[SSL_CERT_PATH]]/fullchain.pem:/config/keys/cert.crt:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/config/keys/cert.key:ro
    ports:
      - 23882:443
    restart: unless-stopped
