---
version: "2.1"
services:
  nextcloud:
    container_name: nextcloud
    image: lscr.io/linuxserver/nextcloud:latest
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - [[INSTALL_PATH]]/nextcloud:/config
      - [[APP_MOUNT_POINT]]/nextcloud/data:/data
      - /DATA/SSLCerts/fullchain.pem:/config/keys/cert.crt:ro
      - /DATA/SSLCerts/privkey.pem:/config/keys/cert.key:ro
    ports:
      - 23882:443
    restart: unless-stopped
