---
services:
  perplexica:
    image: itzcrazykns1337/perplexica:latest
    container_name: perplexica
    volumes:
      - [[INSTALL_PATH]]/perplexica/data:/home/perplexica/data
      - [[INSTALL_PATH]]/perplexica/uploads:/home/perplexica/uploads
      - [[SSL_CERT_PATH]]/fullchain.pem:/certs/fullchain.pem:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/certs/privkey.pem:ro
    ports:
      - 9118:3001
    restart: unless-stopped
    entrypoint:
      - sh
      - -c
      - |
        echo ""
        echo "─────────────────────────────────────────────────────────────"
        echo ""
        echo "   Running official image from itzcrazykns1337/perplexica"
        echo "   Modified at runtime for SSL support by HomeDock OS team"
        echo "   Visit: https://www.homedock.cloud/"
        echo ""
        echo "─────────────────────────────────────────────────────────────"
        echo ""
        cat > /home/perplexica/ssl-proxy.js << 'EOFPROXY'
        const https = require('https');
        const http = require('http');
        const fs = require('fs');
        const os = require('os');

        const httpsOptions = {
          key: fs.readFileSync('/certs/privkey.pem'),
          cert: fs.readFileSync('/certs/fullchain.pem')
        };

        const targetHost = os.hostname();

        https.createServer(httpsOptions, (req, res) => {
          const options = {
            hostname: targetHost,
            port: 3000,
            path: req.url,
            method: req.method,
            headers: req.headers
          };
          const proxy = http.request(options, (proxyRes) => {
            res.writeHead(proxyRes.statusCode, proxyRes.headers);
            proxyRes.pipe(res, { end: true });
          });
          req.pipe(proxy, { end: true });
          proxy.on('error', (err) => {
            console.error('Proxy error:', err);
            res.writeHead(502);
            res.end('Bad Gateway');
          });
        }).listen(3001, '0.0.0.0', () => {
          console.log('> HTTPS Proxy ready on https://0.0.0.0:3001 -> http://' + targetHost + ':3000');
        });
        EOFPROXY
        export HOSTNAME=0.0.0.0
        /home/perplexica/entrypoint.sh &
        sleep 5
        exec node /home/perplexica/ssl-proxy.js
