---
services:
  retroarch:
    image: lscr.io/linuxserver/retroarch:latest
    container_name: retroarch
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CUSTOM_USER=[[HD_USER_NAME]]
      - PASSWORD=[[HD_PASSWORD]]
      - KASM_SSL_CERT=/config/ssl/cert.pem
      - KASM_SSL_KEY=/config/ssl/cert.key
      - SELKIES_UI_TITLE="RetroArch"
      - SELKIES_UI_SHOW_LOGO=false
    volumes:
      - [[INSTALL_PATH]]/retroarch:/config
      - [[SSL_CERT_PATH]]/fullchain.pem:/config/ssl/cert.pem:ro
      - [[SSL_CERT_PATH]]/privkey.pem:/config/ssl/cert.key:ro
    ports:
      - 30300:3001
    shm_size: "1gb"
    restart: unless-stopped