---
version: '3.3'
services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: unless-stopped
    volumes:
      - [[INSTALL_PATH]]/vaultwarden:/data/
      - /DATA/SSLCerts:/ssl:ro
    ports:
      - "4444:80"
    environment:
      - ROCKET_TLS={certs="/ssl/fullchain.pem",key="/ssl/privkey.pem"}
