---
services:
    wordpress:
        image: wordpress:latest
        container_name: wordpress
        depends_on:
            - wordpress_mariadb
        volumes:
            - [[INSTALL_PATH]]/wordpress/wordpress:/var/www/html
            - /DATA/SSLCerts/fullchain.pem:/etc/ssl/certs/fullchain.pem:ro
            - /DATA/SSLCerts/privkey.pem:/etc/ssl/private/privkey.pem:ro
        environment:
            - WORDPRESS_DB_USER=[[HD_USER_NAME]]
            - WORDPRESS_DB_PASSWORD=[[HD_SYSTEM_PASSWORD]]
            - WORDPRESS_DB_HOST=wordpress_mariadb
            - HTTPS_PORT=38080
        ports:
            - 38080:443
        restart: unless-stopped
        labels:
            HDGroup: "wordpress"
            HDRole: "main"
        command: >
            sh -c "
            echo 'ServerName localhost' >> /etc/apache2/apache2.conf &&
            sed -i 's|/etc/ssl/certs/ssl-cert-snakeoil.pem|/etc/ssl/certs/fullchain.pem|g' /etc/apache2/sites-available/default-ssl.conf &&
            sed -i 's|/etc/ssl/private/ssl-cert-snakeoil.key|/etc/ssl/private/privkey.pem|g' /etc/apache2/sites-available/default-ssl.conf &&
            a2enmod ssl &&
            a2ensite default-ssl &&
            docker-entrypoint.sh apache2-foreground
            "
    wordpress_mariadb:
        image: mariadb:latest
        container_name: wordpress_mariadb
        volumes:
            - [[INSTALL_PATH]]/wordpress/mariadb:/var/lib/mysql
        environment:
            - MYSQL_ROOT_PASSWORD=[[HD_SYSTEM_PASSWORD]]
            - MYSQL_DATABASE=wordpress
            - MYSQL_USER=[[HD_USER_NAME]]
            - MYSQL_PASSWORD=[[HD_SYSTEM_PASSWORD]]
        restart: unless-stopped
        labels:
            HDGroup: "wordpress"
            HDRole: "dependency"

