"""
hd_FunctionsConfig.py
Copyright © 2023-2026 Banshee, All Rights Reserved
See LICENSE.md or https://polyformproject.org/licenses/strict/1.0.0/
https://www.banshee.pro
"""

import os
import re
import time
import stat as stat_module
import bcrypt
import hashlib
import tempfile
import configparser

from pymodules.hd_FunctionsGlobals import current_directory, compose_upload_folder, running_OS
from pymodules.hd_ExternalDriveManager import get_default_external_drive

# HDOS00127
_process_umask = os.umask(0)
os.umask(_process_umask)

_DEFAULT_CONFIG_MODE = 0o666 & ~_process_umask

ALLOWED_DISKSPLUS_SESSION_MINUTES = (0, 3, 5, 10, 15)
ALLOWED_LANGUAGES = ("en", "es", "de", "fr", "it", "pt", "zh", "ru", "uk", "ja", "ko")
ALLOWED_CLOCK_FORMATS = ("24h", "12h")
ALLOWED_WEEK_STARTS = ("sunday", "monday")
ALLOWED_APPEARANCES = ("redmond", "cupertino")


def _clamp_session_timeout(value):
    try:
        minutes = int(value)
    except (TypeError, ValueError):
        return 10
    return minutes if minutes in ALLOWED_DISKSPLUS_SESSION_MINUTES else 10


def _clamp_language(value):
    if isinstance(value, str) and value in ALLOWED_LANGUAGES:
        return value
    return "en"


def _clamp_clock_format(value):
    if isinstance(value, str) and value in ALLOWED_CLOCK_FORMATS:
        return value
    return "24h"


def _clamp_week_start(value):
    if isinstance(value, str) and value in ALLOWED_WEEK_STARTS:
        return value
    return "monday"


def _clamp_appearance(value):
    if isinstance(value, str) and value in ALLOWED_APPEARANCES:
        return value
    return "redmond"


def check_and_generate_config():
    config_file = os.path.join(current_directory, "homedock_server.conf")

    default_external_drive = get_default_external_drive()

    password_input = "passwd".encode("utf-8")
    salt = bcrypt.gensalt()
    hashed_password = bcrypt.hashpw(password_input, salt)
    hashed_password_str = hashed_password.decode("utf-8")

    if not os.path.exists(config_file):
        config = configparser.ConfigParser()
        config["Config"] = {
            "user_name": "user",
            "user_password": hashed_password_str,
            "run_port": "80",
            "dynamic_dns": "get.homedock.cloud",
            "local_dns": "True",
            "run_on_development": "False",
            "disable_usage_data": "False",
            "delete_old_image_containers_after_update": "False",
            "delete_old_image_containers_after_uninstall": "False",
            "delete_internal_data_volumes": "True",
            "reverse_proxy": "False",
            "local_http_access": "False",
            "acme_provider": "",
            "acme_token": "",
            "dynamic_dns_sync": "False",
            "default_external_drive": default_external_drive,
            "require_protected_paths_password": "True",
            "disksplus_session_timeout_minutes": "10",
            "selected_theme": "default",
            "selected_back": "back1.jpg",
            "selected_appearance": "redmond",
            "selected_language": "en",
            "clock_format": "24h",
            "week_start": "monday",
            "2fa_enabled": "False",
            "2fa_secret": "False",
            "2fa_backup_codes": "False",
            "2fa_whitelist_hashes": "False",
        }

        write_config(config, config_file)

        print()
        print(" * Default configuration file missing, it has been autogenerated")

    check_and_update_password(config_file)
    check_and_update_config()

    if not os.path.exists(compose_upload_folder):
        os.makedirs(compose_upload_folder)


def check_and_update_password(config_file):
    config = configparser.ConfigParser()
    config.read(config_file)

    user_password = config.get("Config", "user_password")

    if not re.match(r"^\$2b\$[0-9]{2}\$[./A-Za-z0-9]{53}$", user_password):
        if len(user_password) > 30:
            print("Error: Please provide a password shorter than 30 characters.")
            exit(1)

        print(" * Detected plaintext password. Hashing now...")
        salt = bcrypt.gensalt()
        hashed_password = bcrypt.hashpw(user_password.encode("utf-8"), salt).decode("utf-8")

        config.set("Config", "user_password", hashed_password)
        write_config(config, config_file)

        print(" * Password has been hashed and saved to configuration.")


def check_and_update_config():
    config_file = os.path.join(current_directory, "homedock_server.conf")
    config = configparser.ConfigParser()

    if os.path.exists(config_file):
        config.read(config_file)

        missing_options = []

        if not config.has_option("Config", "disable_usage_data"):
            config.set("Config", "disable_usage_data", "False")
            missing_options.append("disable_usage_data")

        if not config.has_option("Config", "delete_internal_data_volumes"):
            config.set("Config", "delete_internal_data_volumes", "False")
            missing_options.append("delete_internal_data_volumes")

        if not config.has_option("Config", "2fa_enabled"):
            config.set("Config", "2fa_enabled", "False")
            missing_options.append("2fa_enabled")

        if not config.has_option("Config", "2fa_secret"):
            config.set("Config", "2fa_secret", "False")
            missing_options.append("2fa_secret")

        if not config.has_option("Config", "2fa_backup_codes"):
            config.set("Config", "2fa_backup_codes", "False")
            missing_options.append("2fa_backup_codes")

        if not config.has_option("Config", "2fa_whitelist_hashes"):
            config.set("Config", "2fa_whitelist_hashes", "False")
            missing_options.append("2fa_whitelist_hashes")

        if not config.has_option("Config", "reverse_proxy"):
            config.set("Config", "reverse_proxy", "False")
            missing_options.append("reverse_proxy")

        # HDOS00074
        if not config.has_option("Config", "local_http_access"):
            config.set("Config", "local_http_access", "False")
            missing_options.append("local_http_access")

        # HDOS00065
        if not config.has_option("Config", "acme_provider"):
            config.set("Config", "acme_provider", "")
            missing_options.append("acme_provider")

        if not config.has_option("Config", "acme_token"):
            config.set("Config", "acme_token", "")
            missing_options.append("acme_token")

        # HDOS00109
        if not config.has_option("Config", "dynamic_dns_sync"):
            config.set("Config", "dynamic_dns_sync", "False")
            missing_options.append("dynamic_dns_sync")

        if not config.has_option("Config", "require_protected_paths_password"):
            config.set("Config", "require_protected_paths_password", "True")
            missing_options.append("require_protected_paths_password")

        if not config.has_option("Config", "disksplus_session_timeout_minutes"):
            config.set("Config", "disksplus_session_timeout_minutes", "10")
            missing_options.append("disksplus_session_timeout_minutes")

        if not config.has_option("Config", "selected_language"):
            config.set("Config", "selected_language", "en")
            missing_options.append("selected_language")

        if not config.has_option("Config", "clock_format"):
            config.set("Config", "clock_format", "24h")
            missing_options.append("clock_format")

        if not config.has_option("Config", "week_start"):
            config.set("Config", "week_start", "monday")
            missing_options.append("week_start")

        if not config.has_option("Config", "selected_appearance"):
            config.set("Config", "selected_appearance", "redmond")
            missing_options.append("selected_appearance")

        if missing_options:
            write_config(config, config_file)
            print(f" * Added missing configuration options: {', '.join(missing_options)}")

    else:
        print("Configuration file does not exist. Generate it first.")


def is_fresh_install():
    try:
        config = read_config()
        user_name = config.get("user_name", "")
        stored = config.get("user_password")
        if not stored:
            return False
        if isinstance(stored, str):
            stored = stored.encode("latin1")
        if user_name.lower() != "user":
            return False
        return bcrypt.checkpw(b"passwd", stored)
    except Exception:
        return False


# HDOS00124
def write_config(config, path=None):
    # HDOS00127
    target = os.path.realpath(path or os.path.join(current_directory, "homedock_server.conf"))

    descriptor, temporary = tempfile.mkstemp(dir=os.path.dirname(target) or ".", prefix=".homedock_server.conf.")

    try:
        with os.fdopen(descriptor, "w") as stream:
            config.write(stream)
            stream.flush()
            os.fsync(stream.fileno())

        # HDOS00127
        try:
            mode = stat_module.S_IMODE(os.stat(target).st_mode)
        except OSError:
            mode = _DEFAULT_CONFIG_MODE

        try:
            os.chmod(temporary, mode)
        except OSError:
            pass

        # HDOS00004 HDOS00125
        for attempt in range(10):
            try:
                os.replace(temporary, target)
                break
            except PermissionError:
                if attempt == 9:
                    raise
                time.sleep(0.02)

    except BaseException:
        try:
            os.unlink(temporary)
        except OSError:
            pass

        raise


# HDOS00123
_config_cache = {"entry": None}


# HDOS00126
def _config_signature(path):
    try:
        with open(path, "rb") as handle:
            return hashlib.blake2b(handle.read(), digest_size=16).digest()
    except OSError:
        return None


def read_config():
    path = os.path.join(current_directory, "homedock_server.conf")

    signature = _config_signature(path)

    # HDOS00123
    entry = _config_cache["entry"]

    if entry is not None and signature is not None and entry[0] == signature:
        return dict(entry[1])

    config = configparser.ConfigParser()
    config.read(path)

    try:
        run_port = config.getint("Config", "run_port")
        if run_port < 80 or run_port > 65535:
            print("Error: Invalid port number in configuration file. Must be between 80 and 65535.")
            print("Using default port 80, select any other port by modifying homedock_server.conf!")
            run_port = 80
    except ValueError:
        print("Error: Invalid port number in configuration file. Please make sure it's an integer.")
        print("Using default port 80, select any other port by modifying homedock_server.conf!")
        run_port = 80

    config_dict = {
        "user_name": config.get("Config", "user_name"),
        "user_password": config["Config"]["user_password"].encode("latin1"),
        "run_port": run_port,
        "local_dns": config.getboolean("Config", "local_dns"),
        "dynamic_dns": config.get("Config", "dynamic_dns"),
        "selected_theme": config.get("Config", "selected_theme"),
        "selected_back": config.get("Config", "selected_back"),
        "run_on_development": config.getboolean("Config", "run_on_development"),
        "disable_usage_data": config.getboolean("Config", "disable_usage_data"),
        "delete_old_image_containers_after_update": config.getboolean("Config", "delete_old_image_containers_after_update"),
        "delete_old_image_containers_after_uninstall": config.getboolean("Config", "delete_old_image_containers_after_uninstall"),
        "delete_internal_data_volumes": config.getboolean("Config", "delete_internal_data_volumes"),
        "default_external_drive": config.get("Config", "default_external_drive"),
        "2fa_enabled": config.getboolean("Config", "2fa_enabled"),
        "2fa_secret": config.get("Config", "2fa_secret"),
        "2fa_backup_codes": config.get("Config", "2fa_backup_codes"),
        "2fa_whitelist_hashes": config.get("Config", "2fa_whitelist_hashes", fallback=""),
        "reverse_proxy": config.getboolean("Config", "reverse_proxy", fallback=False),
        "local_http_access": config.getboolean("Config", "local_http_access", fallback=False),
        "acme_provider": config.get("Config", "acme_provider", fallback=""),
        "acme_token": config.get("Config", "acme_token", fallback=""),
        "dynamic_dns_sync": config.getboolean("Config", "dynamic_dns_sync", fallback=False),
        "require_protected_paths_password": config.getboolean("Config", "require_protected_paths_password", fallback=True),
        "disksplus_session_timeout_minutes": _clamp_session_timeout(config.get("Config", "disksplus_session_timeout_minutes", fallback="10")),
        "selected_language": _clamp_language(config.get("Config", "selected_language", fallback="en")),
        "clock_format": _clamp_clock_format(config.get("Config", "clock_format", fallback="24h")),
        "week_start": _clamp_week_start(config.get("Config", "week_start", fallback="monday")),
        "selected_appearance": _clamp_appearance(config.get("Config", "selected_appearance", fallback="redmond")),
    }

    # HDOS00123
    if signature is not None:
        _config_cache["entry"] = (signature, config_dict)

    return dict(config_dict)
